const IMG={logo:'assets/img/studio-prism.png',av:'assets/img/archivision.jpg',app:'assets/img/prism-app.jpg',game:'assets/img/prism-game.jpg',p3d:'assets/img/prism-3d.jpg'};
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.3});
const $=s=>document.querySelector(s),E=n=>n.toLocaleString('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:2});
const UV={av:['Maquettes numériques & BIM','ArchiVision est le projet de Studio Prism dédié à l’exploration des maquettes numériques et des projets BIM. Il permet de visualiser, explorer, isoler, analyser et mesurer un projet afin de mieux comprendre le bâtiment et ses données.'],app:['Applications, interfaces & produits numériques','Studio Prism conçoit des applications et produits numériques pensés autour des usages réels. De l’interface au fonctionnement, nous transformons une idée ou un besoin métier en une expérience claire, cohérente et utilisable.'],p3d:['Modélisation 3D & visualisation','Prism 3D transforme une idée ou un modèle numérique en objet concret, de la modélisation au prototypage et à la fabrication.'],game:['Création interactive & 3D temps réel','Prism Game explore le jeu vidéo et les expériences interactives à travers la création d’univers, de mécaniques et de prototypes en 3D temps réel.']};
const B={app:{n:'Prism App',c:'var(--cyan)'},game:{n:'Prism Game',c:'var(--turq)'},p3d:{n:'Prism 3D',c:'var(--a3)'},studio:{n:'Studio',c:'var(--prism)'}};


const G=[['Shift Factory','Tycoon / automatisation','Construire et optimiser une petite usine en débloquant des machines.'],['Parcel Rush','Livraison / course','Livrer des colis dans une ville compacte et améliorer son équipement.'],['Tiny Café','Gestion / simulation','Gérer un petit café et le développer progressivement.'],['Mine & Craft','Collecte / fabrication','Explorer, récolter et fabriquer pour accéder à de nouvelles ressources.'],['Sky Islands','Exploration / construction','Développer une île volante et explorer les îles voisines.'],['Metro District','Simulation / rôle','Construire et faire fonctionner un quartier avec différents rôles.'],['Blackout Protocol','Coopération / survie','Rétablir l’énergie d’une installation malgré une menace.'],['Driftline','Course / personnalisation','Courses urbaines et véhicules qui évoluent.'],['Relic Hunters','Aventure / donjons','Explorer des ruines, résoudre des énigmes, récupérer des reliques.'],['PRISM: The Shattered World','Action-RPG / monde persistant','Explorer un monde fragmenté et découvrir son histoire.']];
// Prix indicatifs
const P=[['clip','Clip range-câble','Bureau','Maintenir des câbles sur un poste de travail.',6],['passe','Passe-câble de bureau','Bureau','Guider les câbles à travers un plateau.',9],['tel','Support de téléphone compact','Bureau','Tenir un téléphone à un angle de lecture stable.',12],['croc','Crochet léger','Maison','Accrocher des accessoires légers.',5],['sach','Clip de fermeture de sachet','Maison','Refermer un sachet au quotidien.',4],['cas','Support de casque audio','Bureau','Poser un casque et libérer de la place.',18],['usb','Organiseur USB','Bureau','Garder plusieurs câbles séparés.',10],['plan','Pied pour petite plante','Maison','Surélever un petit pot.',7],['mark','Marque-page géométrique','Maison','Petit objet léger et personnalisable.',5],['key','Porte-clés Prism','Marque','Mini-gamme à l’effigie de Prism.',6]];
const COLS=['Bleu nuit','Turquoise','Cyan','Blanc'],CH=['#071B55','#169999','#1F89C5','#ffffff'];
const PR={app:'Mockup smartphone + tablette affichant une maquette BIM 3D, UI claire, fond #F2F7FA, accents #1F89C5',game:'Capture de jeu Roblox low-poly, UI lisible, palette turquoise #169999',p3d:'Rendu produit réaliste d’un objet imprimé 3D sur un bureau, lumière douce, accents bleu nuit'};
const ITEMS=[{n:'ArchiVision',b:'app',s:'En conception',d:UV.av[1],l:'#/projets/archivision'},...G.map(g=>({n:g[0],b:'game',s:'Concept',d:g[2],g:1})),...P.map(p=>({n:p[1],b:'p3d',s:'Concept',d:p[3],p:p[0]}))];
const ART={
'ArchiVision':'<path d="M44 120V72l40-18 70 18v48M44 72l40 12 70-12M84 54v66M120 77v43M146 74v46"/><path d="M26 120h188" stroke-width="4"/><path class="f" d="M184 30l22 12v24l-22 12-22-12V42z"/><path d="M184 30v24M162 42l22 12 22-12"/>',
'Shift Factory':'<path d="M44 118V76l24 12V76l24 12V76l24 12V54h34v64z"/><path d="M134 54V34h14v20"/><rect class="f" x="58" y="98" width="14" height="20"/><circle cx="192" cy="98" r="13"/><circle cx="192" cy="98" r="4"/><path d="M28 126h184"/>',
'Parcel Rush':'<path d="M36 110V70h62v40M98 84h22l14 18v8"/><circle cx="62" cy="114" r="9"/><circle cx="118" cy="114" r="9"/><rect class="f" x="150" y="62" width="42" height="38"/><path d="M150 78h42M171 62v16M16 92h14M10 102h20"/>',
'Tiny Café':'<path d="M68 66h72v36a24 24 0 0 1-24 24H92a24 24 0 0 1-24-24z"/><path d="M140 76h8a14 14 0 0 1 0 28h-12"/><path d="M92 54c-6-8 6-12 0-20M114 54c-6-8 6-12 0-20M72 82h64M52 134h112"/>',
'Mine & Craft':'<path d="M54 124l66-66"/><path d="M90 50c24-10 52 4 60 32"/><path class="f" d="M168 86l24-12 24 12v28l-24 12-24-12z"/><path d="M168 86l24 12 24-12M192 98v28"/>',
'Sky Islands':'<path class="f" d="M56 88h128c-8 22-34 36-64 42-30-6-56-20-64-42z"/><circle cx="120" cy="52" r="14"/><path d="M120 66v22M184 40h30c-2 8-10 12-15 14-5-2-13-6-15-14zM30 54h28M24 66h22"/>',
'Metro District':'<path d="M28 124V86h22v38M50 124V58h28v66M78 124V76h22v48M100 124V40h30v84M130 124V72h24v52M154 124V92h24v32M178 124V66h22v58"/><path d="M22 124h196M110 56h10M110 72h10M110 88h10M58 74h8M58 90h8"/>',
'Blackout Protocol':'<circle cx="120" cy="76" r="54" stroke-dasharray="10 12"/><path class="f" d="M130 30L92 82h30l-10 40 44-58h-30z"/>',
'Driftline':'<path d="M44 108l10-22q4-8 14-8h56q10 0 16 8l14 14q12 2 12 12v8H44z"/><path d="M76 78l-6 18h54l-12-18z"/><circle cx="76" cy="116" r="9"/><circle cx="164" cy="116" r="9"/><path d="M14 126c24 0 40 8 64 8M10 138c28 0 52 4 78 4"/>',
'Relic Hunters':'<path d="M52 124V62h20v62M168 124V72h20v52M44 62h36M160 72h36M36 124h168"/><path class="f" d="M120 48l24 24-24 40-24-40z"/><path d="M96 72h48M120 48v64"/>',
'PRISM: The Shattered World':'<path d="M120 22l46 26v54l-46 26-46-26V48z"/><path d="M120 22l-8 42 32 10-14 54M74 48l38 16-20 42"/><path class="f" d="M180 30l16 10-8 16z"/><path d="M60 126l-14 10"/>',
'Clip range-câble':'<path d="M72 120V72a48 48 0 0 1 96 0v48z"/><circle class="f" cx="120" cy="84" r="16"/><path d="M14 118c40 0 60-34 106-34s66 34 106 34"/>',
'Passe-câble de bureau':'<path d="M24 74l36-18h120l36 18-36 18H60z"/><ellipse class="f" cx="120" cy="74" rx="28" ry="11"/><path d="M120 85v32c0 12 24 8 24 24"/>',
'Support de téléphone compact':'<rect x="90" y="30" width="48" height="84" rx="8" transform="rotate(-14 114 72)"/><path d="M76 124h96M96 124l20-16"/><path class="f" d="M70 126h104v6H70z"/>',
'Crochet léger':'<rect class="f" x="98" y="24" width="44" height="12" rx="4"/><path d="M120 36v52a22 22 0 0 0 44 0"/><circle cx="164" cy="97" r="9"/><path d="M164 106v14"/>',
'Clip de fermeture de sachet':'<path d="M58 50h124l-10 80H68z"/><rect class="f" x="96" y="36" width="48" height="20" rx="6"/><path d="M108 56v10M132 56v10"/>',
'Support de casque audio':'<path d="M84 98V86a36 36 0 0 1 72 0v12"/><rect class="f" x="72" y="94" width="18" height="30" rx="8"/><rect class="f" x="150" y="94" width="18" height="30" rx="8"/><path d="M120 134V52M96 136h48"/>',
'Organiseur USB':'<rect class="f" x="56" y="84" width="128" height="32" rx="8"/><path d="M92 84v32M120 84v32M148 84v32"/><path d="M76 84c0-22 10-30 10-48M104 84c0-18 8-30 8-48M136 84c0-22-8-30-8-48M164 84c0-18-10-28-10-48"/>',
'Pied pour petite plante':'<path d="M98 78h44l-6 26h-32z"/><path d="M84 106h72M92 106l-8 22M148 106l8 22"/><path d="M120 78V54M120 64c-12 0-18-10-18-18 12 0 18 8 18 18M120 58c10 0 18-8 18-16-12 0-18 6-18 16"/><path class="f" d="M84 106h72v6H84z"/>',
'Marque-page géométrique':'<path class="f" d="M92 26h56v96l-28-22-28 22z"/><path d="M92 54h56M120 26v32M92 54l28 20 28-20"/>',
'Porte-clés Prism':'<circle cx="120" cy="36" r="12"/><path d="M120 48v14"/><path class="f" d="M120 62l30 17v34l-30 17-30-17V79z"/><path d="M120 96l30-17M120 96l-30-17M120 96v34"/>'};
const art=n=>`<svg viewBox="0 0 240 150" fill="none" stroke="#bfeeee" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" role="img" aria-label="${n}">${ART[n]||''}</svg>`;

const PH={KM:'',PC:''};
const teamH=()=>`<div id="equipe" class="k">Équipe</div><h2>L’équipe</h2><div class="team">${[['KM','Kéliann MAUGER','Fondateur · Développeur web &amp; 3D'],['PC','Paul COCAGNE','Co-fondateur · Développeur outils &amp; 3D']].map(([a,n,r])=>`<div class="tm"><figure class="ph" role="img" aria-label="Emplacement photo : ${n}">${PH[a]?`<img src="${PH[a]}" alt="${n}" loading="lazy">`:`<span aria-hidden="true">${a}</span>`}</figure><h3>${n}</h3><p class="mt2">${r}</p></div>`).join('')}</div>`;
const PQM=[`<svg viewBox="0 0 120 120" fill="none" stroke="currentColor" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"><path d="M8 108h104" stroke-dasharray="2 5"/><path d="M12 96C34 96 38 70 56 66S86 56 98 34 108 18 110 12"/><circle cx="12" cy="96" r="2.5"/><circle cx="36" cy="82" r="3.2"/><circle cx="56" cy="66" r="4"/><circle cx="98" cy="34" r="4.8"/></svg>`,`<svg viewBox="0 0 120 120" fill="none" stroke="currentColor" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"><path d="M8 40h104M8 108h104"/><path d="M78 38L8 108M78 38L40 108M78 38V108M78 38L116 108"/><circle cx="78" cy="38" r="3"/></svg>`,`<svg viewBox="0 0 120 120" fill="none" stroke="currentColor" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"><circle cx="16" cy="60" r="5"/><path d="M21 60C40 60 44 28 62 28M21 60H62M21 60C40 60 44 92 62 92"/><circle cx="66" cy="28" r="4"/><circle cx="66" cy="60" r="4"/><circle cx="66" cy="92" r="4"/><path d="M70 28C82 28 84 16 96 16M70 28C82 28 84 40 96 40"/><circle cx="100" cy="16" r="3"/><circle cx="100" cy="40" r="3"/></svg>`,`<svg viewBox="0 0 120 120" fill="none" stroke="currentColor" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"><path d="M8 108H34V86H60V64H86V42H112" /><path d="M8 108L112 42" stroke-dasharray="2 5"/><circle cx="112" cy="42" r="3.5"/></svg>`];
const apropos=()=>V(`<section class="pg"><div class="w"><div class="k">Studio Prism</div><h2>Pourquoi Studio Prism existe</h2><ul class="pq">${[['Notre histoire','Réunir logiciel, création interactive et fabrication numérique au sein d’un même studio.'],['Notre vision','Transformer des idées en réalisations utiles, documentées et capables d’évoluer.'],['Nos branches','Studio Prism comme groupe ; Prism App, Prism Game et Prism 3D comme pôles spécialisés.'],['Notre méthode','Comprendre → concevoir → prototyper → tester → documenter → améliorer.']].map(([a,b],i)=>`<li class="pq-i rv"><div class="pq-b"><div class="pq-h"><span class="pq-n" aria-hidden="true">0${i+1}</span><span class="pq-r" aria-hidden="true"></span></div><span class="pq-g" aria-hidden="true">${PQM[i]}</span><div class="pq-t"><h3>${a}</h3><p>${b}</p></div></div></li>`).join('')}</ul><div style="margin-top:56px">${teamH()}</div><p style="margin-top:36px"><a class="btn b1" href="#/projets">Voir les projets</a><a class="btn b4" href="#/contact">Nous contacter</a></p></div></section>`);
const card=i=>`<a class="card" href="${i.g?'#/prism-game/'+slug(i.n):i.p?'#/prism-3d/'+i.p:i.l}">${i.n=='ArchiVision'?lgo('av','Logo ArchiVision','ls-c'):`<div class="im ${{app:'ia',game:'ig',p3d:'i3'}[i.b]}">${art(i.n)}</div>`}<div class="t"><span class="tag">${B[i.b].n}</span><span class="tag">${i.s}</span><h3>${i.n}</h3><p>${i.d}</p></div></a>`;
let raf=0,cart=[],S={pf:'all',gf:'all',bc:'all',bm:'all',slot:null,day:0,rt:1,step:1,last:'',v3:null};
let lastH;const V=h=>{const y=scrollY,keep=lastH===H();lastH=H();$('#v').innerHTML=mo()+h;document.querySelectorAll('#v .rv').forEach(e=>io2.observe(e));window.SP&&window.SP.cms&&window.SP.cms.view();scrollTo({top:keep?y:0,behavior:'instant'})};
function modal(h){const m=document.createElement('div');m.className='mod';m.innerHTML=`<div class="panel" role="dialog" aria-modal="true" aria-label="Détails" tabindex="-1">${h}<p style="margin-top:14px"><button class="btn b4" data-a="x">Fermer</button></p></div>`;m._f=document.activeElement;document.body.appendChild(m);m.querySelector('.panel').focus()}
const badge=()=>$('#cc').textContent=cart.reduce((a,l)=>a+l.q,0);
/* ---- 3D ---- */
function mount3d(el,mode,opt={}){
 if(!window.THREE){el.innerHTML='<p style="padding:24px">Visualiseur 3D indisponible hors-ligne.</p>';return}
 const w=el.clientWidth||400,h=el.clientHeight||340,r=new THREE.WebGLRenderer({antialias:true,alpha:true});r.setSize(w,h);r.setPixelRatio(Math.min(devicePixelRatio,2));el.appendChild(r.domElement);
 const s=new THREE.Scene(),c=new THREE.PerspectiveCamera(40,w/h,.1,100),g=new THREE.Group(),Z=mode=='bim'?9:5;c.position.z=Z;s.add(g,new THREE.AmbientLight(0xffffff,.65));const L=new THREE.DirectionalLight(0xffffff,.9);L.position.set(3,5,4);s.add(L);
 const mk=(geo,col)=>new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:col,metalness:.2,roughness:.45,flatShading:true}));
 const a={g,meshes:[],auto:!matchMedia('(prefers-reduced-motion:reduce)').matches,mk};
 if(mode=='prism'){a.main=mk(new THREE.CylinderGeometry(1,1,1.5,6),0x1F89C5);g.add(a.main);g.rotation.x=.5}
 else{[0x9aa7b8,0x1F89C5,0x169999].forEach(()=>0);for(let f=0;f<4;f++){const y=f*1.1-1.6,sl=mk(new THREE.BoxGeometry(4,.12,3),0x9aa7b8),wl=mk(new THREE.BoxGeometry(3.6,.9,2.6),0x1F89C5),rs=mk(new THREE.BoxGeometry(3.4,.08,.14),0x169999);sl.position.y=y;wl.position.y=y+.51;rs.position.y=y+.9;wl.material.transparent=true;wl.material.opacity=.7;sl.userData={n:'Dalle — niveau '+f,cat:0,mat:'Béton'};wl.userData={n:'Murs — niveau '+f,cat:1,mat:'Brique'};rs.userData={n:'Gaine technique — niveau '+f,cat:2,mat:'Acier'};g.add(sl,wl,rs);a.meshes.push(sl,wl,rs)}g.rotation.x=.45}
 let d=0,px=0,py=0,mv=0;const cv=r.domElement,rc=new THREE.Raycaster();
 cv.onpointerdown=e=>{d=1;a.auto=false;px=e.clientX;py=e.clientY;mv=0;cv.setPointerCapture(e.pointerId)};
 cv.onpointermove=e=>{if(!d)return;g.rotation.y+=(e.clientX-px)*.01;g.rotation.x+=(e.clientY-py)*.01;mv+=Math.abs(e.clientX-px)+Math.abs(e.clientY-py);px=e.clientX;py=e.clientY};
 cv.onpointerup=e=>{d=0;if(mode=='bim'&&mv<5){const b=cv.getBoundingClientRect();rc.setFromCamera({x:(e.clientX-b.left)/b.width*2-1,y:-((e.clientY-b.top)/b.height)*2+1},c);const hit=rc.intersectObjects(a.meshes.filter(m=>m.visible))[0];a.meshes.forEach(m=>m.material.emissive.setHex(0));if(hit){hit.object.material.emissive.setHex(0x113355);opt.pick&&opt.pick(hit.object.userData)}}};
 cv.onwheel=e=>{e.preventDefault();c.position.z=Math.min(14,Math.max(2.5,c.position.z+e.deltaY*.005))};
 a.reset=()=>{g.rotation.set(.45,0,0);c.position.z=Z};
 (function loop(){raf=requestAnimationFrame(loop);if(a.auto)g.rotation.y+=.006;r.render(s,c)})();a.dispose=()=>{cancelAnimationFrame(raf);g.traverse(o=>{o.geometry&&o.geometry.dispose();o.material&&o.material.dispose()});r.dispose();r.forceContextLoss();r.domElement.remove()};return a}
/* ---- pages ---- */
const filt=(k,arr)=>`<div class="chips">${arr.map(([v,t])=>`<button class="chip ${S[k]==v?'on':''}" data-a="f" data-k="${k}" data-v="${v}">${t}</button>`).join('')}</div>`;
const folio=()=>`${filt('pf',[['all','Tous'],['app','Prism App'],['game','Prism Game'],['p3d','Prism 3D']])}<div class="g" id="pg">${ITEMS.filter(i=>S.pf=='all'||i.b==S.pf).map(card).join('')}</div>`;
const PL={av:'<path d="M60 220h280M60 220V120l70-40 90 30 120-30v140M130 80v140M220 110v110M340 80v140M60 120l70 28 90-38 120 24M60 245h280M60 239v12M340 239v12"/>',pg:'<path d="M40 210l70-90 60 50 70-100 80 70 40-40M40 210l130-40 110 60 80-90M110 120l60 50-130 40M170 170l110 60-40-20M240 70l40 100M110 120l60-60 70 10"/>',p3:'<path d="M200 70l90 50v100l-90 50-90-50V120zM200 70v100l90 50M200 170l-90 50M110 120l90 50 90-50M320 120v100M314 120h12M314 220h12M90 270h220"/>'};
const plate=id=>`<svg viewBox="0 0 400 300" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><g fill="none" stroke="#8fcfe6" stroke-width="1.3">${PL[id]}</g></svg>`;
const PJ=[['av','01','ArchiVision',UV.av[0],UV.av[1],'BIM · IFC · AR · VR','En conception','#/projets/archivision',''],['pg','02','Prism Game','Interactif / 3D / Temps réel',UV.game[1],'Roblox · 3D · Temps réel','Concept','#/prism-game','r'],['p3','03','Prism 3D','CAO / Prototypage / Fabrication',UV.p3d[1],'CAO · Impression 3D · PLA / PETG','Concept','#/prism-3d','f']];
const pj=([id,n,t,c,d,te,st,l,x])=>`<a class="pj ${x} rv" href="${l}" data-vt="${id}"><div class="pl" data-pl="${id}">${plate(id)}</div><div class="tx"><p class="no">${n}</p><h3>${t}</h3><p class="mt2">${c}</p><p class="d">${d}</p><p class="mt2">${te} · ${st}</p><span class="more">Voir le projet →</span></div></a>`;
const SP=[['applications','Développement d’applications','Web · Mobile · SaaS','Conception fonctionnelle, UX/UI, prototypes, développement et accompagnement de produits numériques.','Parler de votre projet','#/rendez-vous'],['bim-xr','Solutions BIM / XR','BIM · IFC · AR · VR · Visualisation','Visualisation de maquettes, interfaces BIM, expériences AR/VR/XR et outils associés.','Décrire un besoin BIM','#/contact'],['interactif','Expériences interactives','3D · Temps réel · Expériences','Prototypes interactifs, environnements 3D temps réel, mécaniques et systèmes.','Parler de votre projet','#/rendez-vous'],['fabrication','Prototypage &amp; impression 3D','CAO · Prototypage · Impression 3D','Modélisation, prototypage, objets fonctionnels, petites séries et produits Prism 3D.','Demander un devis','#/devis']];
const HSV='<svg class="hsv" viewBox="26 28 494 386" fill="none" stroke="currentColor" role="presentation"><g opacity=".18"><path d="M0 70h520M0 220h520M0 370h520M90 0v440M260 0v440M430 0v440"/></g><path d="M260 60l150 86-150 86-150-86z" fill="#0877B9" fill-opacity=".14" stroke="none"/><path d="M260 232l150-86v172l-150 86z" fill="#169999" fill-opacity=".16" stroke="none"/><g class="dr" stroke-width="1.6"><path d="M260 60l150 86v172l-150 86-150-86V146z"/><path d="M260 60v172l150 86M260 232l-150 86M110 146l150 86 150-86"/></g><g opacity=".5"><path d="M440 146v172M434 146h12M434 318h12M110 360h300M110 354v12M410 354v12"/></g><text x="260" y="44" text-anchor="middle">Conception</text><text x="426" y="138">Technologie</text><text x="94" y="138" text-anchor="end">Réalité</text></svg>';
const SV={applications:{tags:'Applications · Logiciels · Outils numériques',pts:[['Applications &amp; logiciels','Applications web et mobiles, logiciels et outils numériques.'],['UX / UI','Parcours, maquettes et interfaces lisibles.'],['Conception','Cadrage du besoin, périmètre et prototype à valider.'],['Développement','Réalisation, tests et accompagnement du produit.']],rt:'Projet associé',rel:()=>card(ITEMS[0]),note:'ArchiVision est un projet de la branche <a class="more" href="#/prism-app">Prism App</a>.',t:'Un outil à imaginer ?',cta:['Parler de votre projet','#/devis']},
'bim-xr':{tags:'BIM · IFC · AR · VR',pts:[['BIM &amp; maquettes numériques','Maquettes de bâtiments et données associées.'],['IFC','Piste principale de format ; prise en charge réelle selon la complexité des fichiers (tests en cours).'],['Visualisation 3D','Navigation, coupes, isolation et mesure dans le modèle.'],['Réalité augmentée et virtuelle','Consultation de maquettes en AR puis en VR, selon la feuille de route.'],['Consultation de modèles','Des outils d’exploration et d’analyse, pas un logiciel de conception.']],rt:'Projet mis en avant',rel:()=>card(ITEMS[0]),note:'ArchiVision explore, isole, analyse et mesure une maquette numérique.',t:'Voir la démonstration',cta:['Découvrir ArchiVision','#/projets/archivision']},
interactif:{tags:'3D · Temps réel · Immersion',pts:[['Expériences 3D','Environnements et objets explorables.'],['Temps réel','Rendu et réactions immédiates.'],['Interaction','Mécaniques et interfaces à manipuler.'],['Immersion','Expériences numériques centrées sur l’utilisateur.']],rt:'Où cela se prototype',rel:()=>'<a class="card" href="#/prism-game"><div class="t"><span class="tag">Concepts expérimentaux</span><h3>Prism Game</h3><p>Branche créative et expérimentale : prototypes de gameplay et expériences temps réel.</p></div></a>',note:'Les concepts de Prism Game servent de terrain d’exploration pour ces expériences.',t:'Un projet interactif ?',cta:['Parler de votre projet','#/rendez-vous']},
fabrication:{tags:'CAO · Prototypage · Impression 3D',pts:[['Modélisation &amp; CAO','Conception d’objets en 3D.'],['Conception','Du besoin à la forme, avec contraintes d’usage.'],['Prototypage','Premières pièces à tester et ajuster.'],['Impression 3D','PLA et PETG pour commencer.'],['Créations physiques','Objets fonctionnels et petites séries.']],rt:'Créations Prism 3D (concepts)',rel:()=>P.slice(0,3).map(q=>prodCard(q,1)).join(''),note:'Cette page présente le savoir-faire. Les créations sont dans <a class="more" href="#/prism-3d">Prism 3D</a>.',t:'Une pièce à concevoir ?',cta:['Demander un devis','#/devis']}};
function servicePage(id){const v=SV[id],x=SP.find(a=>a[0]==id),i=SP.indexOf(x);V(`<section class="pg"><div class="w"><p class="crumb"><a href="#/services">Expertises</a> / ${x[1]}</p><div class="k">Service 0${i+1}</div><h1>${x[1]}</h1><p class="lead2" style="max-width:720px">${x[3]}</p><p class="mut">${v.tags}</p></div></section>
<section class="alt"><div class="w"><h2>Ce que couvre ce service</h2>${spec(v.pts)}</div></section>
<section><div class="w"><h2>${v.rt}</h2><div class="g">${v.rel()}</div><p style="margin-top:20px">${v.note}</p></div></section>
<section class="dark"><div class="w buy"><h2 style="margin:0">${v.t}</h2><p><a class="btn bw ar" href="${v.cta[1]}">${v.cta[0]}</a><a class="btn b3 ar" href="#/services">Tous les services</a></p></div></section>`)}
const BR=[['av','01','Prism App',UV.app[0],UV.app[1],'#/prism-app',''],['pg','02','Prism Game',UV.game[0],UV.game[1],'#/prism-game','r'],['p3','03','Prism 3D',UV.p3d[0],UV.p3d[1],'#/prism-3d','']],br=([id,n,t,c,d,l,x])=>`<a class="pj br ${x} rv" href="${l}" data-vt="${id}">${lgo({av:'app',pg:'game',p3:'p3d'}[id],'Logo '+t,'',`data-pl="${id}"`)}<div class="tx"><p class="no">${n}</p><h3 style="font-size:28px;margin:4px 0">${t}</h3><p class="mt2">${c}</p><p class="lead2" style="font-size:19px;margin:10px 0">${d}</p><p style="max-width:520px">${UX[{av:'app',pg:'game',p3:'p3d'}[id]][0]}</p><ul class="uxl">${UX[{av:'app',pg:'game',p3:'p3d'}[id]][1].map(t=>`<li>${t}</li>`).join('')}</ul><span class="more">${UX[{av:'app',pg:'game',p3:'p3d'}[id]][2]} →</span></div></a>`;
function home(){V(`<section class="hero2"><div class="w hg"><div><div class="k">Studio Prism</div><h1>Créer des systèmes numériques qui prennent forme.</h1><p class="lead">Nous concevons des applications, expériences interactives, solutions BIM/XR et créations 3D qui relient conception, technologie et réalité.</p><p class="mt2 htags">Applications · BIM / XR · Expériences interactives · Modélisation et impression 3D</p><p><a class="btn b1 ar" href="#/devis">Parler de votre projet</a><a class="btn b4 ar" href="#/projets">Voir les projets</a></p></div><div class="hv" aria-hidden="true">${HSV}</div></div></section>
<section class="pos"><div class="w gcols"><h2 class="rv">Le studio</h2><div class="rv"><p class="lead2">Réunir logiciel, création interactive et fabrication numérique au sein d’un même studio.</p><p><a class="more" href="#/a-propos">À propos de Studio Prism →</a></p></div></div></section>
<section class="alt"><div class="w"><h2 class="rv">Expertises</h2><div class="sp">${SP.map(([id,t,te],i)=>`<a class="rv" href="#/services/${id}"><p class="no">0${i+1}</p><h3>${t}</h3><p class="mt2">${te}</p></a>`).join('')}</div><p style="margin-top:28px"><a class="more" href="#/services">Voir les expertises →</a></p></div></section>
<section class="dark"><div class="w"><div class="feat rv"><div><span class="tag">Prism App</span><span class="tag">BIM / XR / Application</span><span class="tag">En conception</span><h2 style="margin:10px 0">ArchiVision</h2><p class="lead2">${UV.av[1]}</p><p style="max-width:560px;margin-bottom:14px">${UX.av[0]}</p><p class="mt2" style="margin-bottom:20px">Explorer · Isoler · Analyser · Mesurer</p><a class="btn bw ar" href="#/projets/archivision">Découvrir ArchiVision</a></div>${lgo('av','Logo ArchiVision — Architecture en réalité augmentée')}</div></div></section>
<section><div class="w"><h2 class="rv">Univers</h2><div class="pjs">${BR.map(br).join('')}</div></div></section>
<section class="alt"><div class="w"><div class="mtd-h rv"><h2>Notre méthode</h2><p>De l’idée à une solution concrète, nous avançons par étapes pour donner une forme claire et cohérente à chaque projet.</p></div><ol class="mtd">${[['Comprendre','Nous partons du besoin, du contexte et des objectifs du projet avant de définir la solution.','target'],['Concevoir','L’idée prend la forme d’une structure claire : expérience, interface, fonctionnalités et direction visuelle.','ui'],['Prototyper','Prototypes, maquettes, modèles 3D ou démonstrateurs : le projet prend rapidement forme.','wire'],['Développer','Nous construisons la solution et intégrons les technologies adaptées au projet.','code'],['Faire évoluer','Le projet est testé, ajusté et fait évoluer selon les besoins et les usages.','axes']].map(([t,d,i],n)=>`<li class="mtd-i${n==4?' mtd-w':''} rv"><div class="mtd-b"><div class="mtd-t"><span class="mtd-n" aria-hidden="true">0${n+1}</span><h3>${t}</h3><p>${d}</p></div><span class="mtd-g" aria-hidden="true">${gl(i)}</span></div></li>`).join('')}</ol></div></section>
${prjSec()}<section><div class="w">${teamH()}</div></section>
<section class="dark"><div class="w"><h2 class="rv">Vous avez un projet ?</h2><p class="rv" style="max-width:560px;margin-bottom:24px">Décrivez votre besoin : nous revenons vers vous avec une estimation personnalisée.</p><p><a class="btn bw ar" href="#/devis">Parler de votre projet</a><a class="btn b3 ar" href="#/contact">Nous contacter</a></p></div></section>`)}
function projets(){V(`<section class="pg"><div class="w"><p class="crumb">Studio</p><h1>Réalisations</h1><p class="lead">Les projets majeurs de Studio Prism, les produits mis en avant et les univers où se prototypent les idées.</p><div class="pjs">${pj(PJ[0])}</div><div class="cms-pj-w" hidden><h2 style="margin-top:80px">Réalisations récentes</h2><div class="g" id="cms-pj"></div></div><div class="rfeat" hidden><h2 style="margin-top:80px">Produits mis en avant</h2><p class="mut" style="max-width:640px;margin-bottom:28px">Une sélection du catalogue Studio Prism. <a class="more" href="#/produits">Voir tous les produits →</a></p><div class="g" id="rfeat"></div></div><h2 style="margin-top:80px">Concepts et prototypes</h2><p class="mut" style="max-width:640px;margin-bottom:28px">Ces éléments sont des concepts : ce ne sont ni des produits publiés ni des réalisations pour des clients.</p><div class="sp"><a href="#/prism-game"><p class="no">Prism Game</p><h3>Concepts expérimentaux</h3><p class="mt2">Interactif · 3D · Temps réel</p><p style="margin-top:8px">Prototypes de gameplay et expériences, notamment sur Roblox.</p></a><a href="#/prism-3d"><p class="no">Prism 3D</p><h3>Créations en concept</h3><p class="mt2">CAO · Prototypage · Impression 3D</p><p style="margin-top:8px">Objets conçus en CAO, destinés à être prototypés par impression 3D.</p></a></div></div></section>`);if(window.SP&&window.SP.catalog)window.SP.catalog.mount($('#rfeat'),{featured:true,exclude:['archivision'],hideIfEmpty:'.rfeat'});if(window.SP&&window.SP.cms)window.SP.cms.mountProjects($('#cms-pj'))}
function appBranch(){const sv=SP.filter(a=>a[0]=='applications'||a[0]=='bim-xr');V(`<section class="pg"><div class="w">${phero('av','01','Prism App',UV.app[0],'',UV.app[1])}<div class="gpres gp2">${lgo('app','Logo Prism App — Digital Solutions &amp; Interfaces','','data-hero="av"')}${uxb('app')}</div></div></section>
<section class="alt"><div class="w"><div class="k">Rôle de la branche</div><h2 class="rv">Ce que couvre Prism App</h2><div class="sp">${sv.map(([id,t,te,d])=>`<a class="rv" href="#/services/${id}"><h3>${t}</h3><p class="mt2">${te}</p><p style="margin-top:8px">${d}</p></a>`).join('')}</div></div></section>
<section><div class="w"><div class="k">Projets</div><h2 class="rv">Projets Prism App</h2><div class="g" id="pg-app" style="grid-template-columns:repeat(auto-fill,minmax(270px,1fr))"></div></div></section>`);cslot('#pg-app',{pole:'app'},()=>ITEMS.filter(i=>i.b=='app').map(card).join(''))}
function pApp(){V(`<section class="pg"><div class="w">${phero('av','01','ArchiVision','Prism App · BIM / XR / Application','En conception','Explorer la maquette numérique autrement.')}<div class="gpres gp2">${lgo('av','Logo ArchiVision — Architecture en réalité augmentée','','data-hero="av"')}${uxb('av')}</div>${fx()}<div class="cz"><div class="cz-p"><button class="btn b1 ar cz-b" data-a="bimgo">Lancer la démonstration</button></div><p class="cz-a"><a class="cz-l" href="#/archivision/inscription">Créer un compte</a><span class="cz-d" aria-hidden="true">·</span><a class="cz-l" href="#/archivision/connexion">Se connecter</a></p>${proCta()}</div><div id="bimh" style="margin-top:28px"></div><h3 style="margin:36px 0 12px">Feuille de route</h3><table><tr><th>Phase</th><th>Livrable visé</th></tr><tr><td>1 — Viewer</td><td>Charger, orbiter, sélectionner, lire des propriétés</td></tr><tr><td>2 — Robustesse BIM</td><td>Tests IFC, unités, tailles de fichiers</td></tr><tr><td>3 — XR mobile</td><td>Positionnement, échelle, ancrage</td></tr><tr><td>4 — VR</td><td>Navigation adaptée à un casque</td></tr><tr><td>5 — Lunettes AR</td><td>Étude de faisabilité</td></tr></table><p style="margin-top:24px"><a class="btn b1" href="#/devis">Décrire un besoin BIM</a></p></div></section>`)}
/* ===== ArchiVision : démonstration BIM =====
   DEMO_DATA : maquette fictive générée par code. Seules les dimensions (calculées depuis la géométrie), le nom, la catégorie,
   le type et le niveau sont renseignés ; aucune donnée technique n'est simulée au-delà. Les modes Éclatée et XR sont des simulations. */
function bimApp(){const host=$('#bimh');
const CATS=[['arch','Architecture',[['murs','Murs'],['sols','Sols'],['plafonds','Plafonds'],['toiture','Toiture'],['portes','Portes'],['fenetres','Fenêtres']]],['mobilier','Mobilier'],['equipements','Équipements'],['reseaux','Réseaux']],CN={murs:'Mur',sols:'Sol',plafonds:'Plafond',toiture:'Toiture',portes:'Porte',fenetres:'Fenêtre',mobilier:'Mobilier',equipements:'Équipement',reseaux:'Réseau'},LV=['RDC','R+1'],MD=[['3d','3D'],['plan','Plan'],['elev','Élévation'],['coupe','Coupe'],['exp','Vue éclatée'],['xr','XR']],TL=[['sel','Sélection'],['mes','Mesure'],['hid','Masquage'],['iso','Isolation']];
host.innerHTML=`<div class="bim"><div class="bt"><b>ARCHIVISION</b><span>Projet : maison de démonstration</span><span>Bâtiment : R+1</span><span>Vue : <b id="bvw">3D</b></span><span>Mode : <b id="bmd">3D</b></span></div>
<div class="bmodes" role="group" aria-label="Modes d’affichage">${MD.map(([k,t])=>`<button class="chip ${k=='3d'?'on':''}" data-m="${k}" aria-pressed="${k=='3d'}">${t}</button>`).join('')}</div>
<div class="bb"><aside class="bp" aria-label="Structure du modèle"><h3>Structure du modèle</h3><div id="btree">${CATS.map(([k,t,ch])=>ch?`<label class="opt"><input type="checkbox" data-p checked> ${t}</label><div class="bsub">${ch.map(([c,n])=>`<label class="opt"><input type="checkbox" data-c="${c}" checked> ${n}</label>`).join('')}</div>`:`<label class="opt"><input type="checkbox" data-c="${k}" checked> ${t}</label>`).join('')}</div><h3>Niveau</h3><div class="chips" id="blv">${[['all','Tous'],[0,'RDC'],[1,'R+1']].map(([v,t])=>`<button class="chip ${v=='all'?'on':''}" data-lv="${v}">${t}</button>`).join('')}</div></aside>
<div class="bc" id="bc"><div class="btl" role="group" aria-label="Outils">${TL.map(([k,t])=>`<button class="chip ${k=='sel'?'on':''}" data-t="${k}" aria-pressed="${k=='sel'}">${t}</button>`).join('')}<button class="chip" data-t="reset">Tout réafficher</button></div><div class="bz"><button class="chip" data-z="1" aria-label="Zoom avant">+</button><button class="chip" data-z="-1" aria-label="Zoom arrière">−</button></div><div class="bcut" id="bcut" hidden><label>Position de la coupe<input type="range" id="bcr" min="-5" max="5" step=".1" value="0"></label></div><p class="bxr" id="bxr" hidden>Simulation AR : la maquette est posée sur site à échelle réduite (démonstration).</p></div>
<aside class="bp" aria-label="Élément"><h3>Élément</h3><div id="binf"></div><div id="bms" aria-live="polite"></div><p class="mut" style="font-size:13px;margin-top:16px">Maquette fictive de démonstration. Outil actif : <b id="btn">Sélection</b>.</p></aside></div></div>`;
const bc=$('#bc'),W=()=>bc.clientWidth,Hh=()=>bc.clientHeight,r=new THREE.WebGLRenderer({antialias:true,alpha:true});r.setPixelRatio(Math.min(devicePixelRatio,2));r.setSize(W(),Hh());bc.prepend(r.domElement);const cv=r.domElement;cv.style.touchAction='none';cv.setAttribute('aria-label','Maquette 3D interactive');
const sc=new THREE.Scene(),cam=new THREE.PerspectiveCamera(40,W()/Hh(),.1,200),grp=new THREE.Group(),grid=new THREE.GridHelper(26,26,0xb4c2d0,0xcdd8e2),ground=new THREE.Mesh(new THREE.CircleGeometry(11,48),new THREE.MeshBasicMaterial({color:0x9cb888}));ground.rotation.x=-Math.PI/2;ground.position.y=-.21;ground.visible=false;grid.position.y=-.2;
const dl=new THREE.DirectionalLight(0xffffff,.7);dl.position.set(6,12,8);sc.add(grp,grid,ground,new THREE.AmbientLight(0xffffff,.78),dl);
const E=[],cn={},mat=(c,o)=>new THREE.MeshStandardMaterial(Object.assign({color:c,roughness:.8,metalness:0,flatShading:true,side:THREE.DoubleSide},o));
function add(geo,c,cat,n,type,lvl,x,y,z,ry,o){const m=new THREE.Mesh(geo,mat(c,o||{}));m.position.set(x,y,z);m.rotation.y=ry||0;if(/^(Mur|Cloison|Fen|Porte|Chaise|Radiat)/.test(n))n+=' '+(cn[n]=(cn[n]||0)+1);m.userData={cat,n,type,lvl,y0:y};m.add(new THREE.LineSegments(new THREE.EdgesGeometry(geo,20),new THREE.LineBasicMaterial({color:0x4a5d75})));grp.add(m);E.push(m);m.updateMatrixWorld(true);m.userData.d=new THREE.Box3().setFromObject(m).getSize(new THREE.Vector3());return m}
const bx=(a,b,c)=>new THREE.BoxGeometry(a,b,c),win=(u,v)=>({u,v,w:1.4,h:1.2,k:'w'}),door=u=>({u,v:0,w:.9,h:2.1,k:'d'});
function wall(l,hh,t,holes,lvl,x,z,ry,type){const s2=new THREE.Shape();s2.moveTo(0,0);s2.lineTo(l,0);s2.lineTo(l,hh);s2.lineTo(0,hh);holes.forEach(o=>{const p=new THREE.Path();p.moveTo(o.u,o.v);p.lineTo(o.u+o.w,o.v);p.lineTo(o.u+o.w,o.v+o.h);p.lineTo(o.u,o.v+o.h);s2.holes.push(p)});
 const g=new THREE.ExtrudeGeometry(s2,{depth:t,bevelEnabled:false});g.translate(-l/2,0,-t/2);const m=add(g,0xf3f5f7,'murs',type,type,lvl,x,lvl?3:0,z,ry);
 holes.forEach(o=>{const d=o.k=='d',c=m.localToWorld(new THREE.Vector3(o.u+o.w/2-l/2,o.v+o.h/2,0));add(bx(o.w,o.h,d?.06:.04),d?0x8a6f55:0x8cc3e6,d?'portes':'fenetres',d?'Porte':'Fenêtre',d?'Porte simple':'Fenêtre fixe',lvl,c.x,c.y,c.z,ry,d?{}:{transparent:true,opacity:.45})})}
add(bx(10,.2,7),0xc9d2db,'sols','Dalle RDC','Dalle béton',0,0,-.1,0);add(bx(10,.2,7),0xc9d2db,'sols','Plancher R+1','Plancher',1,0,2.9,0);
add(bx(9.75,.1,6.75),0xffffff,'plafonds','Plafond RDC','Faux plafond',0,0,2.75,0);add(bx(9.75,.1,6.75),0xffffff,'plafonds','Plafond R+1','Faux plafond',1,0,5.55,0);add(bx(10.4,.25,7.4),0xaab6c3,'toiture','Toiture','Toiture-terrasse',1,0,5.725,0);
[0,1].forEach(l=>{const hh=l?2.5:2.7,v=l?.7:.9,ex='Mur extérieur';wall(10,hh,.25,l?[win(1.2,v),win(4.3,v),win(7.4,v)]:[win(1.2,v),door(4.55),win(7.4,v)],l,0,3.5,0,ex);wall(10,hh,.25,[win(1.2,v),win(4.3,v),win(7.4,v)],l,0,-3.5,0,ex);wall(7,hh,.25,[win(2.8,v)],l,5,0,Math.PI/2,ex);wall(7,hh,.25,[win(2.8,v)],l,-5,0,Math.PI/2,ex);wall(7,hh,.12,[door(3.05)],l,l?1:-1,0,Math.PI/2,'Cloison')});
add(bx(2,.8,.9),0x7d8fa6,'mobilier','Canapé','Assise',0,-3,.4,1.8,0);add(bx(1.6,.75,.9),0xb9a58b,'mobilier','Table à manger','Table',0,2.5,.375,-1,0);add(bx(.45,.9,.45),0xb9a58b,'mobilier','Chaise','Assise',0,1.5,.45,-1,0);add(bx(.45,.9,.45),0xb9a58b,'mobilier','Chaise','Assise',0,3.5,.45,-1,0);add(bx(2,.5,1.6),0x9fb3c8,'mobilier','Lit','Couchage',1,3,3.25,-1.8,0);add(bx(1.2,2,.6),0xb9a58b,'mobilier','Armoire','Rangement',1,-3.5,4,-3,0);
add(bx(.6,1,.5),0x6f7f92,'equipements','Chaudière','Production de chaleur',0,-4.4,.5,-2.9,0);add(bx(1.2,.55,.1),0xdfe6ee,'equipements','Radiateur','Émetteur de chaleur',0,-3.1,.45,3.3,0);add(bx(1.2,.55,.1),0xdfe6ee,'equipements','Radiateur','Émetteur de chaleur',1,-3.1,3.75,3.3,0);add(bx(.4,.4,.6),0xdfe6ee,'equipements','Sanitaire','Appareil sanitaire',0,4.4,.2,-2.8,0);
add(new THREE.CylinderGeometry(.09,.09,5.6,12),0x169999,'reseaux','Colonne montante','Réseau eau',0,-4.7,2.8,-2.4,0);const pg2=new THREE.CylinderGeometry(.05,.05,9,10);pg2.rotateZ(Math.PI/2);add(pg2,0x169999,'reseaux','Réseau d’eau','Réseau eau',0,0,2.55,-2.4,0);add(bx(8,.25,.3),0x8a97a8,'reseaux','Gaine de ventilation','Ventilation',1,0,5.3,-2.4,0);
const on={},hid=new Set(),EXP={sols:0,mobilier:.9,equipements:.9,reseaux:1.8,murs:2.7,portes:2.7,fenetres:2.7,plafonds:4.4,toiture:5.4},goal={t:-.7,p:1.1,d:19},cur=Object.assign({},goal),tg=new THREE.Vector3(0,2.6,0),P1=new THREE.Plane(new THREE.Vector3(0,-1,0),1.3),PX=new THREE.Plane(new THREE.Vector3(-1,0,0),0),rc=new THREE.Raycaster(),VW={'3d':'3D','plan':'Plan','elev':'Élévation','coupe':'Coupe','exp':'Vue éclatée','xr':'3D (XR simulé)'};
Object.keys(CN).forEach(k=>on[k]=true);let lv='all',iso=null,mode='3d',tool='sel',sel=null,clip=null,ex=0,mk=[];
const vis=()=>E.forEach(m=>{const u=m.userData;m.visible=on[u.cat]&&!hid.has(m)&&(!iso||u.cat==iso)&&(lv=='all'||u.lvl==lv)}),fm=v=>v.toFixed(2).replace('.',','),
 pick=m=>{sel&&sel.material.emissive.setHex(0);sel=m;m&&m.material.emissive.setHex(0x0b4f7a);const u=m&&m.userData,d=m&&u.d;$('#binf').innerHTML=m?`<dl class="bdl"><dt>Élément</dt><dd>${u.n}</dd><dt>Catégorie</dt><dd>${CN[u.cat]}</dd><dt>Type</dt><dd>${u.type}</dd><dt>Niveau</dt><dd>${LV[u.lvl]}</dd><dt>Dimensions</dt><dd>${fm(Math.max(d.x,d.z))} × ${fm(d.y)} × ${fm(Math.min(d.x,d.z))} m</dd></dl>`:'<p class="mut">Cliquez sur un élément de la maquette pour consulter ses informations.</p>'},
 clr=()=>{mk.forEach(o=>sc.remove(o));mk=[];$('#bms').textContent=''},
 setMode=k=>{mode=k;clip=null;ex=0;clr();const xr=k=='xr';
  if(k=='3d')Object.assign(goal,{t:-.7,p:1.1,d:19});if(k=='plan'){Object.assign(goal,{t:0,p:.02,d:17});P1.constant=lv==1?4.3:1.3;clip=P1}if(k=='elev')Object.assign(goal,{t:0,p:Math.PI/2,d:24});
  if(k=='coupe'){Object.assign(goal,{t:1.1,p:1.15,d:19});PX.constant=+$('#bcr').value;clip=PX}if(k=='exp'){ex=1;Object.assign(goal,{t:-.7,p:1.15,d:36})}if(xr)Object.assign(goal,{t:-.5,p:1.3,d:15});
  r.clippingPlanes=clip?[clip]:[];grid.visible=!xr;ground.visible=xr;grp.scale.setScalar(xr?.75:1);bc.classList.toggle('xr',xr);$('#bcut').hidden=k!='coupe';$('#bxr').hidden=!xr;$('#bvw').textContent=VW[k];$('#bmd').textContent=MD.find(a=>a[0]==k)[1];
  host.querySelectorAll('[data-m]').forEach(b=>{b.classList.toggle('on',b.dataset.m==k);b.setAttribute('aria-pressed',b.dataset.m==k)})};
pick(null);vis();
const bim=host.firstChild;
bim.onclick=e=>{const b=e.target.closest('[data-m],[data-t],[data-lv],[data-z]');if(!b)return;const d=b.dataset;
 if(d.m)setMode(d.m);if(d.z)goal.d=Math.min(40,Math.max(6,goal.d*(d.z>0?.85:1.18)));
 if(d.lv){lv=d.lv=='all'?'all':+d.lv;if(mode=='plan')P1.constant=lv==1?4.3:1.3;vis();host.querySelectorAll('[data-lv]').forEach(x=>x.classList.toggle('on',x==b))}
 if(d.t=='reset'){hid.clear();iso=null;vis();clr()}else if(d.t){tool=d.t;clr();$('#btn').textContent=b.textContent;host.querySelectorAll('[data-t]').forEach(x=>{const o=x==b;x.classList.toggle('on',o&&d.t!='reset');x.setAttribute('aria-pressed',o)})}};
bim.onchange=e=>{const c=e.target,p=bim.querySelector('[data-p]'),ch=[...bim.querySelectorAll('[data-c]')].filter(x=>CATS[0][2].some(a=>a[0]==x.dataset.c));if(c.dataset.p!==undefined)ch.forEach(x=>{x.checked=c.checked;on[x.dataset.c]=c.checked});else if(c.dataset.c)on[c.dataset.c]=c.checked;
 p.checked=ch.every(x=>x.checked);p.indeterminate=!p.checked&&ch.some(x=>x.checked);vis()};
$('#bcr').oninput=e=>PX.constant=+e.target.value;
let dr=0,px,py,mv;cv.onpointerdown=e=>{dr=1;px=e.clientX;py=e.clientY;mv=0;cv.setPointerCapture(e.pointerId)};
cv.onpointermove=e=>{if(!dr)return;const dx=e.clientX-px,dy=e.clientY-py;mv+=Math.abs(dx)+Math.abs(dy);px=e.clientX;py=e.clientY;if(mode=='plan'||mode=='elev')return;goal.t-=dx*.008;goal.p=Math.min(1.5,Math.max(.15,goal.p-dy*.006));cur.t=goal.t;cur.p=goal.p};
cv.onpointerup=e=>{dr=0;if(mv>5)return;const b=cv.getBoundingClientRect();rc.setFromCamera({x:(e.clientX-b.left)/b.width*2-1,y:-((e.clientY-b.top)/b.height)*2+1},cam);
 const h=rc.intersectObjects(E.filter(m=>m.visible)).find(i=>!clip||clip.distanceToPoint(i.point)>=0),m=h&&h.object;
 if(tool=='mes'){if(ex||mode=='xr'){$('#bms').textContent='La mesure est disponible dans les vues 3D, plan, élévation et coupe.';return}if(!h)return;if(mk.length>=3)clr();const s3=new THREE.Mesh(new THREE.SphereGeometry(.08,12,8),new THREE.MeshBasicMaterial({color:0x0877B9,depthTest:false}));s3.position.copy(h.point);s3.renderOrder=9;sc.add(s3);mk.push(s3);
  if(mk.length==2){const a=mk[0].position,c=mk[1].position,l=new THREE.Line(new THREE.BufferGeometry().setFromPoints([a,c]),new THREE.LineBasicMaterial({color:0x0877B9,depthTest:false}));l.renderOrder=9;sc.add(l);mk.push(l);$('#bms').innerHTML=`<p class="bdist">Distance : <b>${fm(a.distanceTo(c))} m</b></p><p class="mut">Δx ${fm(Math.abs(a.x-c.x))} · Δy ${fm(Math.abs(a.y-c.y))} · Δz ${fm(Math.abs(a.z-c.z))} m</p>`}else $('#bms').textContent='Cliquez un second point.';return}
 if(tool=='hid'&&m){hid.add(m);vis();return}if(tool=='iso'){if(m){iso=iso==m.userData.cat?null:m.userData.cat;vis()}}pick(m||null)};
const rs=()=>{r.setSize(W(),Hh());cam.aspect=W()/Hh();cam.updateProjectionMatrix()};addEventListener('resize',rs);let fr;
(function loop(){fr=requestAnimationFrame(loop);['t','p','d'].forEach(k=>cur[k]+=(goal[k]-cur[k])*.12);tg.y+=((ex?6:2.6)-tg.y)*.12;cam.position.set(tg.x+cur.d*Math.sin(cur.p)*Math.sin(cur.t),tg.y+cur.d*Math.cos(cur.p),tg.z+cur.d*Math.sin(cur.p)*Math.cos(cur.t));cam.lookAt(tg);
 E.forEach(m=>{const u=m.userData;m.position.y+=(u.y0+(ex?EXP[u.cat]+u.lvl*6:0)-m.position.y)*.12});r.render(sc,cam)})();
return{dispose(){cancelAnimationFrame(fr);removeEventListener('resize',rs);sc.traverse(o=>{o.geometry&&o.geometry.dispose();o.material&&o.material.dispose()});r.dispose();r.forceContextLoss();cv.remove()}}}
function pGame(){V(`<section class="pg"><div class="w">${phero('pg','02','Prism Game','Interactif / 3D / Temps réel','Univers expérimental','Concepts et prototypes')}<div class="gpres gp2">${lgo('game','Logo Prism Game — Video Game Development','','data-hero="pg"')}${uxb('game')}</div><h2 style="margin:56px 0 8px">Concepts et produits Prism Game</h2><div class="g" id="gg"></div></div></section>`);gg()}
const slug=n=>n.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const gcard=x=>`<a class="card" href="#/prism-game/${slug(x[0])}"><div class="im ig">${art(x[0])}</div><div class="t"><span class="tag">Concept</span><h3>${x[0]}</h3><p class="mt2">${x[1]}</p><p>${x[2]}</p></div></a>`;
/* grilles de produits alimentées par le catalogue central (js/catalog.js) ; sans lui, repli sur les données du site */
const cslot=(id,o,fb)=>{const el=$(id);if(!el)return;window.SP&&window.SP.catalog?window.SP.catalog.mount(el,o):el.innerHTML=fb()};
const gg=()=>cslot('#gg',{pole:'game',note:['Ces concepts sont en exploration. Ce ne sont ni des jeux publiés ni des réalisations pour des clients.','Chaque fiche indique l’avancement du produit : concept, prototype, bêta ou disponible.']},()=>G.map(gcard).join(''));
const prodCard=(p,c)=>`<a class="card" href="#/${c?'prism-3d':'boutique'}/${p[0]}"><div class="im i3">${art(p[1])}</div><div class="t"><span class="tag">${p[2]}</span><h3>${p[1]}</h3><p>${p[3]}</p>${c?'':`<b>${E(p[4])}</b>`}</div></a>`;
const bg=()=>$('#bg').innerHTML=P.filter(p=>S.bc=='all'||p[2]==S.bc).map(p=>`<article class="card"><a href="#/boutique/${p[0]}"><div class="im i3">${art(p[1])}</div></a><div class="t"><span class="tag">${p[2]}</span><h3>${p[1]}</h3><p>${p[3]}</p><p><b>${E(p[4])}</b> <small class="mut">prix indicatif</small></p><p class="mut" style="font-size:13px">Disponibilité : statut concept</p><p><a class="btn b4" href="#/boutique/${p[0]}">Voir le produit</a><button class="btn b1" data-a="pm" data-id="${p[0]}">Ajouter au panier</button></p></div></article>`).join('');

const spec=r=>`<dl class="spec">${r.map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join('')}</dl>`;
function gamePage(sl){const x=G.find(g=>slug(g[0])==sl);if(!x)return nf();const i=G.indexOf(x),o=[1,2,3].map(k=>G[(i+k)%G.length]);
V(`<div class="gh"><div class="gart" aria-hidden="true">${art(x[0])}</div><div class="w"><p class="crumb"><a href="#/projets">Studio</a> / <a href="#/prism-game">Prism Game</a> / ${x[0]}</p><h1>${x[0]}</h1><p class="gmeta"><span>${x[1]}</span><span>Roblox</span><span>Concept expérimental</span></p><p><button class="btn b1 ar" data-a="goto" data-v="gpr">Découvrir</button><button class="btn bw" data-a="goto" data-v="gcar">Voir les détails</button></p><p class="gnote">Visuel conceptuel : artwork et captures à venir.</p></div></div>
<section id="gpr"><div class="w gpres"><div class="im ig" style="aspect-ratio:4/3" role="img" aria-label="Visuel conceptuel">${art(x[0])}</div><div><h2>Présentation</h2><p class="lead2">${x[2]}</p>${spec([['Genre',x[1]],['Plateforme','Roblox'],['Statut','Concept']])}<p class="mut" style="margin-top:16px">L’univers, ce que fait le joueur et l’expérience visée seront rédigés lorsque le prototype sera jouable. Visuel conceptuel : aucune capture réelle.</p></div></div></section>
<section class="alt"><div class="w"><h2>Gameplay</h2><div class="g3">${['Environnement','Mécaniques','Interface'].map(t=>`<div class="ph2"><span>${t}<br><small>Emplacement prévu, aucune capture disponible</small></span></div>`).join('')}</div></div></section>
<section id="gcar"><div class="w"><h2>Caractéristiques</h2>${spec([['Plateforme','Roblox'],['Genre',x[1]],['Développement','Studio Prism'],['Statut','Concept expérimental']])}</div></section>
<section class="dark"><div class="w"><h2>Statut</h2><p style="max-width:560px;margin-bottom:24px">${x[0]} est un concept expérimental de Prism Game : ce n’est ni un jeu publié ni une réalisation pour un client. Pour en discuter avec l’équipe :</p><a class="btn bw ar" href="#/contact">Nous contacter</a></div></section>
<section><div class="w"><h2>Autres concepts</h2><div class="g">${o.map(gcard).join('')}</div></div></section>`)}
function prodPage(id,c){S.pm={mat:'PLA',col:COLS[0]};const p=P.find(q=>q[0]==id);if(!p)return nf();const i=P.indexOf(p),o=[1,2,3].map(k=>P[(i+k)%P.length]);
V(`<section class="pg"><div class="w"><p class="crumb">${c?'<a href="#/projets">Studio</a> / <a href="#/prism-3d">Prism 3D</a>':''} / ${p[1]}</p><div class="pp"><div class="im i3 pimg">${art(p[1])}<small>Visuel illustratif : rendus et photos à venir</small></div><div><span class="tag">${p[2]}</span><h1 style="font-size:clamp(32px,4vw,52px);margin:10px 0 14px">${p[1]}</h1><p class="lead2">${p[3]}</p>${c?`<p class="mt2" style="margin-bottom:20px">Statut : concept. Dimensions et résistances à confirmer après essais.</p><p><a class="btn b1 ar" href="#/devis">Demander un devis</a></p>`:`<p class="pprice">${E(p[4])} <small>prix indicatif</small></p><p class="mt2" style="margin-bottom:20px">Disponibilité : statut concept. Prix, dimensions et résistances à confirmer après essais.</p><label>Matière</label><div class="chips">${['PLA','PETG'].map((m,i)=>`<button class="chip ${i?'':'on'}" data-a="pmat" data-v="${m}">${m}${i?' (+1 €)':''}</button>`).join('')}</div><label>Couleur : <span id="cn">${COLS[0]}</span></label><div>${COLS.map((c2,i)=>`<button class="sw ${i?'':'on'}" style="background:${CH[i]}" data-a="pcol" data-v="${c2}" aria-label="${c2}"></button>`).join('')}</div><label>Quantité<input id="qt" type="number" inputmode="numeric" min="1" value="1" style="max-width:110px"></label><p style="margin-top:18px"><button class="btn b1 ar" data-a="add" data-id="${p[0]}">Ajouter au panier</button><a class="btn b4" href="#/devis">Demander un devis</a></p>`}</div></div>
<h2 style="margin-top:80px">Description détaillée</h2><p class="lead2" style="max-width:640px">${p[3]} Objet de la gamme ${p[2].toLowerCase()}, conçu en CAO puis fabriqué par impression 3D.</p>
<h2 style="margin-top:64px">Caractéristiques</h2>${spec([['Matériau','PLA ou PETG'],['Procédé','Impression 3D'],['Usage',p[2]],['Dimensions','À confirmer après essais'],['Couleurs',COLS.join(', ')]])}
<h2 style="margin-top:64px">Visualisation</h2><div class="panel dark"><div class="v3" id="pv"></div><div class="chips" style="margin-top:12px">${['Face','Dessus','Côté','3/4'].map((t,k)=>`<button class="chip" data-a="ang" data-v="${k}">${t}</button>`).join('')}<button class="chip" data-a="wire">Fil de fer</button><button class="chip" data-a="auto">Rotation</button><button class="chip" data-a="zm" data-v="1" aria-label="Zoom avant">+</button><button class="chip" data-a="zm" data-v="-1" aria-label="Zoom arrière">−</button></div><p style="font-size:13px;margin-top:10px;opacity:.8">Volume générique de démonstration, pas le modèle de l’objet : le modèle CAO réel le remplacera à la publication des fichiers. Glisser pour tourner.</p></div></div></section>
${c?'':`<section class="dark"><div class="w buy"><div><h2 style="margin:0 0 8px">${p[1]}</h2><p>${E(p[4])} · prix indicatif · PLA ou PETG</p></div><p><button class="btn bw ar" data-a="pm" data-id="${p[0]}">Ajouter au panier</button><a class="btn b3 ar" href="#/devis">Demander un devis</a></p></div></section>`}
<section><div class="w"><h2>Vous pourriez aussi aimer</h2><div class="g">${o.map(q=>prodCard(q,c)).join('')}</div></div></section>`);T3(()=>{S.v3=mount3d($('#pv'),'prism')})}
function pP3D(){V(`<section class="pg"><div class="w">${phero('p3','03','Prism 3D','CAO / Prototypage / Fabrication','Concept','Du numérique vers la matière')}<div class="gpres gp2">${lgo('p3d','Logo Prism 3D — 3D Modeling &amp; Prototyping','','data-hero="p3"')}${uxb('p3d')}</div><div class="panel dark"><div class="v3" id="pv"></div><div class="chips" style="margin-top:14px"><button class="chip" data-a="shp" data-v="0">Prisme</button><button class="chip" data-a="shp" data-v="1">Cube</button><button class="chip" data-a="shp" data-v="2">Nœud</button><button class="chip" data-a="wire">Fil de fer</button><button class="chip" data-a="auto">Rotation</button></div>${[['1F89C5','Cyan'],['169999','Turquoise'],['071B55','Bleu nuit']].map(([h,t])=>`<span class="sw" style="background:#${h}" title="${t}" data-a="col" data-v="${h}"></span>`).join('')}</div><h3 style="margin:40px 0 16px">Créations Prism 3D</h3><div class="g" id="pg-3d"></div><p style="margin-top:28px"><a class="btn b4" href="#/devis">Demander un devis</a></p></div></section>`);cslot('#pg-3d',{pole:'p3d'},()=>P.map(q=>prodCard(q,1)).join(''));T3(()=>{S.v3=mount3d($('#pv'),'prism')})}
function boutique(){V(`<section class="pg"><div class="w"><h2>Boutique</h2><p class="mut" style="margin-bottom:16px">Les créations Prism 3D disponibles à l’achat. Prix indicatifs, dimensions et résistances à confirmer après essais. <a class="more" href="#/prism-3d">Découvrir la branche Prism 3D →</a></p>${filt('bc',[['all','Toutes catégories'],['Bureau','Bureau'],['Maison','Maison'],['Marque','Marque']])}<div class="g" id="bg"></div></div></section>`);bg()}

const sub=()=>cart.reduce((a,l)=>a+l.pr*l.q,0);
function panier(){const s=sub(),sh=s&&s<40?4.9:0;V(`<section class="pg"><div class="w"><h2>Panier</h2>${cart.length?`<div class="panel" style="overflow-x:auto"><table style="min-width:520px"><tr><th></th><th>Produit</th><th>Quantité</th><th>Total</th></tr>${cart.map((l,i)=>`<tr><td style="width:84px"><div class="mth" style="width:68px">${art(l.n)}</div></td><td><b>${l.n}</b><br><small class="mut">${l.mat} · ${l.col} · ${E(l.pr)} l’unité</small></td><td><button class="chip" data-a="q" data-i="${i}" data-d="-1" aria-label="Diminuer la quantité">−</button> ${l.q} <button class="chip" data-a="q" data-i="${i}" data-d="1" aria-label="Augmenter la quantité">+</button></td><td>${E(l.pr*l.q)}<br><button class="chip" data-a="rm" data-i="${i}" aria-label="Supprimer ${l.n}">Supprimer</button></td></tr>`).join('')}</table><p style="margin-top:14px">Sous-total : ${E(s)}</p><p>Livraison : ${sh?E(sh):'offerte dès 40 €'}</p><p class="tot">${E(s+sh)}</p><a class="btn b1" href="#/commande">Commander</a></div>`:'<p>Votre panier est vide.</p><a class="btn b1" href="#/boutique">Parcourir la boutique</a>'}</div></section>`)}
function commande(){if(!cart.length)return go('#/panier');const st=S.step,s=sub();V(`<section class="pg"><div class="w" style="max-width:640px"><h2>Commande — étape ${st}/3</h2><form class="panel" data-f="cmd">${st==1?`<label>Nom complet<input name="n" required autocomplete="name"></label><label>E-mail<input type="email" name="e" required autocomplete="email" inputmode="email"></label><label>Adresse<input name="a" required autocomplete="street-address"></label><div class="row"><label>Code postal<input name="cp" required pattern="[0-9]{5}" inputmode="numeric" autocomplete="postal-code" maxlength="5"></label><label>Ville<input name="v" required autocomplete="address-level2"></label></div>`:st==2?`<label class="opt"><input type="radio" name="l" checked> Standard — 4,90 € (offerte dès 40 €)</label><label class="opt"><input type="radio" name="l"> Retrait / main propre — à confirmer</label>`:`<p>Récapitulatif : <b>${E(s)}</b> hors livraison.</p><p class="mut" style="margin-top:8px">Ce site ne stocke aucune donnée de carte et n’ouvre aucun paiement en ligne. <b>Simulation :</b> aucun débit.</p>`}<p style="margin-top:16px">${st>1?'<button type="button" class="btn b4" data-a="prev">Retour</button>':''}<button class="btn b1">${st<3?'Continuer':'Confirmer (simulation)'}</button></p></form></div></section>`)}
function conf(){V(`<section class="pg"><div class="w c"><h2>Commande confirmée</h2><p>Numéro : <b>${S.last}</b></p><p class="mut">Un e-mail récapitulatif sera envoyé (à brancher). Suivi et retours : <a href="#/support" style="color:var(--cyan)">Support</a>.</p><a class="btn b1" href="#/">Accueil</a></div></section>`)}
const OP={app:['Web ou mobile','UX/UI et design system','Back-end / API','Authentification et base de données','Visualisation 3D / BIM','Réalité augmentée (XR mobile)','Maintenance'],p3d:['Modélisation sur mesure','Prototype (1 pièce)','Petite série','Finition et post-traitement']};
function devis(){V(`<section class="pg"><div class="w" style="max-width:760px"><h2>Demande de devis</h2><form class="panel" data-f="devis"><label>Type de projet</label><div class="chips">${Object.keys(OP).map(k=>`<label class="chip ${S.dq==k||(!S.dq&&k=='app')?'on':''}" style="margin:0"><input type="radio" name="t" value="${k}" class="sr" ${k=='app'?'checked':''}>${B[k].n}</label>`).join('')}</div><div id="ops"></div><label>Délai<select name="d" id="dl"><option value="1.25">Immédiat</option><option value="1" selected>1–3 mois</option><option value=".95">3–6 mois</option></select></label><p class="mut" style="margin-top:14px">Le coût dépend du périmètre (écrans, web ou mobile, back-end, 3D / BIM, réalité augmentée, maintenance). Nous revenons vers vous avec une estimation personnalisée après un premier échange.</p><div class="row"><label>Nom<input name="n" required autocomplete="name"></label><label>E-mail<input type="email" name="e" required autocomplete="email" inputmode="email"></label></div><label>Votre besoin<textarea name="m" rows="3" required></textarea></label><button class="btn b1" style="margin-top:12px">Envoyer la demande</button></form></div></section>`);ops()}
function ops(){const k=document.querySelector('[name=t]:checked').value;$('#ops').innerHTML='<p class="mut" style="margin:10px 0 4px">Éléments concernés (indicatif)</p>'+OP[k].map(t=>`<label class="opt"><input type="checkbox" name="o"> ${t}</label>`).join('')}
function est(){}
const toast=m=>{const t=document.createElement('div');t.className='toast';t.textContent=m;$('#tt').appendChild(t);setTimeout(()=>t.remove(),2600)};
function cnt(lo,hi){const el=$('#est'),f=S.e||[0,0],t0=performance.now(),rm=matchMedia('(prefers-reduced-motion:reduce)').matches;S.e=[lo,hi];(function u(n){const p=rm?1:Math.min(1,(n-t0)/500),k=1-Math.pow(1-p,3);el.textContent=E(Math.round(f[0]+(lo-f[0])*k))+' – '+E(Math.round(f[1]+(hi-f[1])*k));if(p<1)requestAnimationFrame(u)})(t0)}
const RT=[['disc','Échange Découverte',15,'Faire connaissance et cadrer votre idée.'],['cadr','Cadrage Projet / Démo',45,'Périmètre, démonstration et prochaines étapes.'],['atel','Atelier Technique',60,'Architecture, BIM/XR, 3D : une vraie session de travail.']];
const SL=[];for(let m=540;m<=1050;m+=30)if(m<720||m>=840)SL.push(m);
const tm=m=>String(m/60|0).padStart(2,'0')+':'+String(m%60).padStart(2,'0'),ds=d=>d.toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}),dl=m=>m==60?'1 h':m+' min';
const pOff=t=>{const p=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'Europe/Paris',hourCycle:'h23',year:'numeric',month:'numeric',day:'numeric',hour:'numeric',minute:'numeric'}).formatToParts(new Date(t)).map(x=>[x.type,+x.value]));return Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute)-t};
const p2u=(y,m,d,h,mi)=>{const g=Date.UTC(y,m,d,h,mi);return g-pOff(g-pOff(g))};
const ev=()=>{const r=S.r,m=RT.find(x=>x[0]==r.m),s=p2u(r.d.getFullYear(),r.d.getMonth(),r.d.getDate(),r.t/60|0,r.t%60);return{s,e:s+m[2]*6e4,z:t=>new Date(t).toISOString().replace(/[-:]|\.\d{3}/g,''),t:'Studio Prism — '+m[1],d:'Réf. '+r.ref+'. Lien Google Meet joint à l’invitation.'}};
function rdv(){S.r={s:1,m:null,d:null,t:null,mo:0};rv();scrollTo(0,0)}
function rv(){const r=S.r,m=RT.find(x=>x[0]==r.m),tz=Intl.DateTimeFormat().resolvedOptions().timeZone||'—',bk=n=>`<button type="button" class="btn b4" data-a="rgo" data-v="${n}">Retour</button>`;let b='';
 if(r.s==5){const v=ev(),f=r.f,g='https://calendar.google.com/calendar/render?action=TEMPLATE&text='+encodeURIComponent(v.t)+'&dates='+v.z(v.s)+'/'+v.z(v.e)+'&details='+encodeURIComponent(v.d),o='https://outlook.live.com/calendar/0/deeplink/compose?path=/calendar/action/compose&subject='+encodeURIComponent(v.t)+'&startdt='+new Date(v.s).toISOString()+'&enddt='+new Date(v.e).toISOString()+'&body='+encodeURIComponent(v.d);
  $('#v').innerHTML=`<section class="pg"><div class="w" style="max-width:680px"><div class="panel"><div class="okc">✓</div><h2 class="c" style="margin-bottom:6px">Rendez-vous confirmé</h2><p class="c mut">Référence <b>${r.ref}</b> · confirmation envoyée à ${f.e}</p><table style="margin:22px 0"><tr><td>Format</td><td><b>${m[1]}</b> · ${dl(m[2])}</td></tr><tr><td>Date</td><td><b style="text-transform:capitalize">${ds(r.d)}</b></td></tr><tr><td>Heure</td><td><b>${tm(r.t)}–${tm(r.t+m[2])}</b> (heure de Paris)</td></tr><tr><td>Participant</td><td>${f.n}${f.c?' — '+f.c:''}</td></tr>${f.fl?`<tr><td>Fichier</td><td>${f.fl}</td></tr>`:''}</table><p style="margin:18px 0 8px"><b>Ajouter à mon calendrier</b></p><a class="btn b1" href="${g}" target="_blank" rel="noopener">Google Agenda</a><a class="btn b4" href="${o}" target="_blank" rel="noopener">Outlook</a><button class="btn b4" data-a="ics">Fichier .ics</button><p class="mut" style="font-size:13px;margin-top:12px">Version de démonstration : l’envoi des e-mails et la création réelle du lien Meet demandent le branchement à Google Agenda.</p><p style="margin-top:12px"><button class="btn b4" data-a="rdv0">Prendre un autre rendez-vous</button></p></div></div></section>`;return}
 if(r.s==1)b=`<h3>Quel type d’échange ?</h3><div class="g" style="margin-top:16px">${RT.map(x=>`<button type="button" class="rtc ${r.m==x[0]?'on':''}" data-a="rtype" data-v="${x[0]}"><span class="tag">${dl(x[2])}</span><b>${x[1]}</b><span class="mut">${x[3]}</span></button>`).join('')}</div>`;
 else if(r.s==2){const base=new Date();base.setDate(1);base.setMonth(base.getMonth()+r.mo);const y=base.getFullYear(),mo=base.getMonth(),n=new Date(y,mo+1,0).getDate(),off=(base.getDay()+6)%7,t0=new Date();t0.setHours(0,0,0,0);let c='';for(let i=0;i<off;i++)c+='<i></i>';
  for(let d=1;d<=n;d++){const dt=new Date(y,mo,d),ok=dt>t0&&dt.getDay()%6&&dt-t0<6e9;c+=`<button type="button" class="day ${r.d&&+r.d==+dt?'on':''}" ${ok?`data-a="dpick" data-v="${y}-${mo}-${d}"`:'disabled'} aria-label="${dt.toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'})}" aria-pressed="${!!(r.d&&+r.d==+dt)}">${d}</button>`}
  b=`<h3 style="margin-bottom:14px">Choisissez un jour</h3><div class="cal-h"><button type="button" class="chip" data-a="mo" data-v="-1" ${r.mo<1?'disabled':''} aria-label="Mois précédent">‹</button><b>${base.toLocaleDateString('fr-FR',{month:'long',year:'numeric'})}</b><button type="button" class="chip" data-a="mo" data-v="1" ${r.mo>=2?'disabled':''} aria-label="Mois suivant">›</button></div><div class="cal">${['L','M','M','J','V','S','D'].map(x=>`<small>${x}</small>`).join('')}${c}</div>${bk(1)}`}
 else if(r.s==3)b=`<h3>Choisissez une heure</h3><p class="mut" style="margin:6px 0 16px;text-transform:capitalize">${ds(r.d)}</p><div class="pills">${SL.map((t,i)=>{const no=(r.d.getDate()*7+i*3+r.d.getMonth())%5==0||t+m[2]>1080;return `<button type="button" class="pill ${r.t===t?'on':''}" ${no?'disabled':`data-a="tpick" data-v="${t}"`}>${tm(t)}</button>`}).join('')}</div><p style="margin-top:20px">${bk(2)} <button type="button" class="btn b1" data-a="rgo" data-v="4" ${r.t==null?'disabled':''}>Continuer</button></p>`;
 else b=`<h3 style="margin-bottom:6px">Parlez-nous de votre projet</h3><form data-f="rdv"><div class="row"><label>Nom complet<input name="n" required autocomplete="name"></label><label>E-mail professionnel<input type="email" name="e" required autocomplete="email"></label></div><div class="row"><label>Entreprise<input name="c" autocomplete="organization"></label><label>Téléphone<input type="tel" name="p" autocomplete="tel"></label></div><label>Décrivez votre besoin<textarea name="m" rows="4" required></textarea></label><div class="row"><label>Lien utile (brief, maquette…)<input type="url" name="l" placeholder="https://" inputmode="url"></label><label>Fichier joint<input type="file" name="fi"></label></div><label class="opt"><input type="checkbox" required> J’accepte le traitement de mes données pour cette demande.</label><p style="margin-top:12px">${bk(3)} <button class="btn b1">Confirmer le rendez-vous</button></p></form>`;
 $('#v').innerHTML=`<section class="pg"><div class="w" style="max-width:980px"><h2>Prendre rendez-vous</h2><p class="mut" style="margin:-14px 0 22px">Réservez un créneau avec l’équipe Studio Prism en quelques clics.</p><div class="stp">${['Format','Date','Heure','Vos infos'].map((t,i)=>`<button type="button" class="${r.s==i+1?'on':''} ${r.s>i+1?'ok':''}" ${r.s>i+1?`data-a="rgo" data-v="${i+1}"`:'disabled'}>${r.s>i+1?'✓':i+1}. ${t}</button>`).join('')}</div><div class="rg"><div class="panel">${b}</div><aside class="panel sum"><small class="mut">Récapitulatif</small><h3>${m?m[1]:'Format à choisir'}</h3>${m?`<p>${dl(m[2])}</p>`:''}<p style="text-transform:capitalize">${r.d?''+ds(r.d):'Date à choisir'}</p><p>${r.t!=null?''+tm(r.t)+'–'+tm(r.t+m[2])+' (Paris)':'Heure à choisir'}</p><p class="mut">Votre fuseau détecté : ${tz}. Créneaux affichés en heure de Paris.</p></aside></div></div></section>`}
function support(){V(`<section class="pg"><div class="w" style="max-width:640px"><h2>Support</h2><form class="panel" data-f="tck"><label>Type de demande<select><option>Projet numérique</option><option>Projet BIM / XR</option><option>Impression 3D</option><option>Autre</option></select></label><label>Sujet<input required></label><label>Description<textarea rows="4" required></textarea></label><button class="btn b1" style="margin-top:12px">Créer le ticket</button></form><div id="tk"></div><p style="margin-top:20px">Réponses rapides : <a href="#/faq" style="color:var(--cyan)">FAQ</a></p></div></section>`)}
function faq(){const Q=[['Comment démarre un projet ?','Par un échange de cadrage, puis un prototype minimal à valider avant toute production complète.'],['Quels formats BIM sont acceptés ?','L’IFC est la piste principale. La prise en charge réelle dépend de la complexité des fichiers (tests en cours).'],['Quels matériaux pour les objets 3D ?','PLA et PETG pour commencer. Les performances sont annoncées seulement après essais.'],['Peut-on personnaliser un objet ?','Oui : logo, initiales, dimensions. Demandez un devis.'],['Comment est établi un devis ?','Le coût dépend du périmètre : dimensions, matériau, quantité, complexité, finition et délai pour une pièce 3D ; écrans, back-end, 3D / BIM et maintenance pour une application. Une estimation personnalisée est proposée après un échange.']];V(`<section class="pg"><div class="w" style="max-width:760px"><h2>Questions fréquentes</h2>${Q.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</div></section>`)}
function contact(){V(`<section class="pg"><div class="w" style="max-width:640px"><h2>Contact</h2><form class="panel" data-f="ct"><label>Nom<input required autocomplete="name"></label><label>E-mail<input type="email" required autocomplete="email" inputmode="email"></label><label>Message<textarea rows="4" required></textarea></label><label class="opt"><input type="checkbox" required> J’accepte le traitement de mes données (voir confidentialité)</label><button class="btn b1">Envoyer</button></form></div></section>`)}
const LG={'mentions-legales':'Mentions légales','cgv-cgu':'CGV / CGU','confidentialite':'Politique de confidentialité','cookies':'Cookies'};
const legal=k=>V(`<section class="pg"><div class="w" style="max-width:760px"><p class="crumb">Informations</p><h1 style="font-size:clamp(32px,4vw,48px)">${LG[k]}</h1><p class="mut">Dernière mise à jour : [À COMPLÉTER]</p>${LT[LK[k]].map(([h,t])=>`<h3 class="lh">${h}</h3><p>${t}</p>`).join('')}<p class="mut" style="margin-top:32px">Les mentions [À COMPLÉTER] sont des informations obligatoires non renseignées : ce texte doit être complété et validé avant publication.</p></div></section>`);
const merci=(t,x)=>V(`<section class="pg"><div class="w c"><h2>${t}</h2><p>Référence : <b>${S.last}</b></p><p class="mut">${x}</p><a class="btn b1" href="#/">Retour à l’accueil</a></div></section>`);
function nf(){V(`<section class="pg"><div class="w c"><h1>404</h1><p>Page introuvable. Attrape 10 prismes pour retrouver ton chemin.</p><canvas id="cv" width="320" height="380"></canvas><p id="sc">Score : 0</p><a class="btn b1" href="#/">Accueil</a></div></section>`);
 const cv=$('#cv'),x=cv.getContext('2d');let px=160,it=[],sc=0,t=0;const mv=e=>{const b=cv.getBoundingClientRect();px=(e.clientX-b.left)/b.width*320};cv.onpointermove=mv;cv.onpointerdown=mv;
 (function L(){raf=requestAnimationFrame(L);t++;if(t%35==0)it.push({x:Math.random()*290+15,y:0,v:2+Math.random()*2});x.fillStyle='#071B55';x.fillRect(0,0,320,380);
 it=it.filter(o=>{o.y+=o.v;if(o.y>350&&Math.abs(o.x-px)<34){sc++;return false}x.fillStyle='#169999';x.beginPath();for(let i=0;i<6;i++)x[i?'lineTo':'moveTo'](o.x+12*Math.cos(i*Math.PI/3),o.y+12*Math.sin(i*Math.PI/3));x.fill();return o.y<380});
 x.fillStyle='#1F89C5';x.fillRect(px-30,360,60,10);$('#sc').textContent=sc>=10?'Bravo ! Score : '+sc:'Score : '+sc})()}
const SHOP=false; /* boutique masquée : passer à true pour la réactiver (routes, panier et données conservés) */
const R={'':home,projets,'prism-app':appBranch,'prism-game':pGame,'prism-3d':pP3D,'a-propos':apropos,boutique,panier,commande,'confirmation-commande':conf,devis,'rendez-vous':rdv,support,faq,contact,'merci-devis':()=>merci('Demande de devis reçue','Nous revenons vers vous sous quelques jours. Vous pouvez aussi réserver un échange.'),'merci-contact':()=>merci('Message envoyé','Merci, nous vous répondons rapidement.')};
/* ---- routeur ---- */
history.scrollRestoration='manual';
let CUR=location.hash.replace(/^#\/?/,'');const H=()=>'#/'+CUR;
const SC={},PID={'prism-app':'av','projets/archivision':'av','prism-game':'pg','projets/prism-game':'pg','prism-3d':'p3','projets/prism-3d':'p3'},rmo=()=>matchMedia('(prefers-reduced-motion:reduce)').matches;
const io2=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io2.unobserve(e.target)}}),{threshold:.1});
const phero=(id,n,t,c,st,sub)=>`<p class="crumb"><a href="#/projets">Studio</a> / ${id=='av'&&t!='Prism App'?'<a href="#/prism-app">Prism App</a> / ':''}${t}</p><p class="meta"><span>${n} — ${c}</span>${st?`<span>Statut : ${st}</span>`:''}</p><h1>${t}</h1><p class="lead">${sub}</p>`;
const T3=f=>{const key=CUR,run=()=>{if(CUR==key&&$('#bv,#pv,#bimh'))f()};if(window.THREE)return run();const t=document.createElement('script');t.src='https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js';t.onload=run;t.onerror=()=>{const e=$('#bv,#pv,#bimh');e&&(e.innerHTML='<p style="padding:24px">Visualiseur 3D indisponible hors-ligne.</p>')};document.head.appendChild(t)};
const mq=matchMedia('(max-width:980px)'),navSt=()=>{const n=$('nav'),o=n.classList.contains('open');n.inert=mq.matches&&!o;$('#bur').setAttribute('aria-expanded',o)},closeDD=d=>{d.classList.remove('open');d.firstElementChild.setAttribute('aria-expanded','false')};
mq.addEventListener('change',navSt);
function navTo(o){const de=document.documentElement,pn=id=>id&&document.querySelector('[data-pl="'+id+'"]'),el=o.el,hr=el&&el.getAttribute('href')||'',kd=!el?'':el.closest('.sv')?'svc':(el.closest('.card')&&/^#\/(boutique|prism-3d)\//.test(hr))?'shop':'',sr=kd=='svc'?el.closest('.sv').querySelector('.no'):kd=='shop'?el.closest('.card').querySelector('.im'):null;
 const run=()=>{route();const dt=kd&&$(kd=='svc'?'#v .k':'#v .pimg');dt&&(dt.style.viewTransitionName='vt-'+kd);let y=o.back?SC[CUR]||0:0;const a=S.anc;S.anc=0;if(a){const t=document.getElementById(a);t&&(y=t.getBoundingClientRect().top+scrollY-(parseInt(getComputedStyle(de).getPropertyValue('--hh'))||90)-16)}
  const c=pn(PID[o.from]);if(c){c.style.viewTransitionName='proj-'+PID[o.from];c.closest('.rv')?.classList.add('in')}
  scrollTo({top:y,behavior:'instant'});$('#v').focus({preventScroll:true})};
 if(rmo()||!document.startViewTransition)return run();
 const c=pn(o.card);c&&(c.style.viewTransitionName='proj-'+o.card);sr&&(sr.style.viewTransitionName='vt-'+kd);
 de.dataset.vt=kd||((o.card||PID[CUR]||(PID[o.from]&&/^(projets)?$/.test(CUR)))?'proj':'page');
 document.startViewTransition(run).finished.catch(()=>{}).finally(()=>{delete de.dataset.vt;document.querySelectorAll('[data-pl],[style*="vt-"]').forEach(e=>e.style.viewTransitionName='')})}
function go(h,o={}){const k=h.replace(/^#\/?/,''),prev=CUR;if(k===CUR)return;SC[CUR]=scrollY;try{history.pushState(null,'','#/'+k)}catch(e){}CUR=k;navTo({...o,from:prev})}
addEventListener('popstate',()=>{const prev=CUR;SC[CUR]=scrollY;CUR=location.hash.replace(/^#\/?/,'');navTo({back:1,from:prev})});
document.addEventListener('click',e=>{if(!e.target.closest('.dd'))document.querySelectorAll('.dd.open').forEach(closeDD);const a=e.target.closest('a[href^="#/"]');if(!a||e.button||e.metaKey||e.ctrlKey||e.shiftKey)return;e.preventDefault();go(a.getAttribute('href'),{card:a.dataset.vt,el:a})});
document.addEventListener('keydown',e=>{const m=$('.mod');if(e.key=='Escape'){m?A.x():document.querySelectorAll('.dd.open').forEach(closeDD);if($('nav').classList.contains('open'))A.bur()}
 if(m&&e.key=='Tab'){const f=[...m.querySelectorAll('button,input,select,textarea,a[href]')],i=f.indexOf(document.activeElement);if(e.shiftKey&&i<1){f[f.length-1].focus();e.preventDefault()}else if(!e.shiftKey&&(i<0||i==f.length-1)){f[0].focus();e.preventDefault()}}});

const services=()=>V(`<section class="pg"><div class="w"><div class="k">Services</div><h1>Que peut-on demander à Studio Prism ?</h1>${SP.map(([id,t,te,d,c,l],i)=>`<div class="sv rv" id="s-${id}"><p class="no">0${i+1}</p><div><h3>${t}</h3><p class="mt2">${te}</p></div><div><p style="margin-bottom:16px">${d}</p><a class="btn b4 ar" href="#/services/${id}">Voir le service</a></div></div>`).join('')}<div class="panel" style="margin-top:40px"><h3>Tarification</h3><p class="mut" style="margin-top:8px">Pas de grille de prix fixe : le coût dépend du périmètre. Le parcours est le même pour chaque projet : étude du besoin, échange, estimation personnalisée, devis.</p><p style="margin-top:16px"><a class="btn b1 ar" href="#/devis">Demander un devis</a></p></div></div></section>`);
Object.assign(R,{services,'projets/archivision':pApp,'projets/prism-game':pGame,'projets/prism-3d':pP3D,confirmation:conf});
Object.assign(LG,{cgv:'CGV',cgu:'CGU','politique-confidentialite':'Politique de confidentialité'});
function route(){const OLD={abonnement:'abonnements',paiement:'abonnements','mon-abonnement':'compte'};if(OLD[CUR]){CUR=OLD[CUR];try{history.replaceState(null,'','#/'+CUR)}catch(e){}}if(!SHOP&&/^(boutique|panier|commande|confirmation)/.test(CUR)){CUR='';try{history.replaceState(null,'','#/')}catch(e){}}A.mcx();cancelAnimationFrame(raf);const v=S.v3;v&&v.dispose&&v.dispose();S.v3=null;$('nav').classList.remove('open');navSt();document.querySelectorAll('.dd.open').forEach(closeDD);
 const k=H().replace(/^#\/?/,''),sk=k.split('/');document.body.dataset.r=k||'home';if(k=='a-propos/equipe')S.anc='equipe';if(sk[0]=='services'&&sk[1])S.anc='s-'+sk[1];
 document.querySelectorAll('nav a').forEach(a=>{const on=a.getAttribute('href')=='#/'+k||(a.classList.contains('nv-pr')&&sk[0]=='produits');a.classList.toggle('on',on);on?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current')});document.querySelectorAll('.dd>button').forEach(b=>b.classList.toggle('on',!!b.parentNode.querySelector('a.on')));
 (R[k]||(k=='a-propos/equipe'?R['a-propos']:sk[0]=='services'?(sk[1]&&SV[sk[1]]?()=>servicePage(sk[1]):R.services):sk[0]=='prism-game'&&sk[1]?()=>gamePage(sk[1]):sk[0]=='prism-3d'&&sk[1]?()=>prodPage(sk[1],1):sk[0]=='boutique'&&sk[1]?()=>prodPage(sk[1]):sk[0]=='abonnements'&&sk[1]?R.abonnements:sk[0]=='produits'&&sk[1]?R['produits-fiche']:LG[k]?()=>legal(k):sk[0]=='p'&&sk.length==2&&(window.SP||{}).cms?()=>window.SP.cms.customPage(sk[1]):sk[0]=='projets'&&sk.length==2&&(window.SP||{}).cms?()=>window.SP.cms.projectPage(sk[1]):sk[0]=='admin'&&sk[1]&&R['admin/'+sk[1]]?R['admin/'+sk[1]]:nf))();
  const h=$('#v h1,#v h2');document.title=(k&&h?h.textContent.trim()+' — ':'')+'Studio Prism — Creative & Technical Solutions';$('#ann').textContent=document.title;window.SP&&window.SP.cms&&window.SP.cms.after()}

/* ---- actions ---- */
const A={x(){const m=document.querySelector('.mod');if(m){m.remove();m._f&&m._f.focus&&m._f.focus()}},skip(){$('#v').focus()},goto(a){document.getElementById(a.dataset.v).scrollIntoView({behavior:rmo()?'auto':'smooth'})},bimgo(a){a.disabled=true;T3(()=>{S.v3=bimApp();a.remove();$('#bimh').scrollIntoView({behavior:rmo()?'auto':'smooth'})})},dd(b){const d=b.parentNode,o=!d.classList.contains('open');document.querySelectorAll('.dd.open').forEach(closeDD);if(o){d.classList.add('open');b.setAttribute('aria-expanded','true')}},
 f(a){S[a.dataset.k]=a.dataset.v;({pf:()=>$('#pg')&&(H()=='#/projets'?projets():home()),gf:()=>{pGame()},bc:()=>boutique()})[a.dataset.k]()},

 pm(a){const p=P.find(p=>p[0]==a.dataset.id);S.pm={mat:'PLA',col:COLS[0]};modal(`<div class="im i3 mh">${art(p[1])}</div><span class="tag">${p[2]}</span><h3>${p[1]}</h3><p class="mut">${p[3]}</p><label>Matière</label><div class="chips">${['PLA','PETG'].map((m,i)=>`<button class="chip ${i?'':'on'}" data-a="pmat" data-v="${m}">${m}${i?' (+1 €)':''}</button>`).join('')}</div><label>Couleur : <span id="cn">${COLS[0]}</span></label><div>${COLS.map((c,i)=>`<button class="sw ${i?'':'on'}" style="background:${CH[i]}" data-a="pcol" data-v="${c}" aria-label="${c}"></button>`).join('')}</div><label>Quantité<input id="qt" type="number" inputmode="numeric" min="1" value="1"></label><p style="margin-top:14px"><button class="btn b1" data-a="add" data-id="${p[0]}">Ajouter au panier</button></p>`)},
 pmat(a){S.pm.mat=a.dataset.v;a.parentNode.querySelectorAll('.chip').forEach(b=>b.classList.toggle('on',b==a))},
 pcol(a){S.pm.col=a.dataset.v;(a.closest('.mod')||document).querySelector('#cn').textContent=a.dataset.v;a.parentNode.querySelectorAll('.sw').forEach(b=>b.classList.toggle('on',b==a))},
 add(a){const sc=a.closest('.mod')||document,p=P.find(p=>p[0]==a.dataset.id),mat=S.pm.mat,col=S.pm.col,q=Math.max(1,+sc.querySelector('#qt').value||1),pr=p[4]+(mat=='PETG'?1:0),src=sc.querySelector('.mh')||sc.querySelector('.pimg');let l=cart.find(l=>l.id==p[0]&&l.mat==mat&&l.col==col);if(l)l.q+=q;else cart.push(l={id:p[0],n:p[1],mat,col,q,pr});fly(src,()=>{badge();bump()});A.x();mcOpen(l,q);$('#ann').textContent=p[1]+' ajouté au panier'},rm(a){cart.splice(+a.dataset.i,1);badge();panier()},
 q(a){const l=cart[a.dataset.i];l.q+=+a.dataset.d;if(l.q<1)cart.splice(a.dataset.i,1);badge();panier()},
 prev(){S.step--;commande()},bur(){$('nav').classList.toggle('open');navSt()},
 rtype(a){S.r.m=a.dataset.v;S.r.s=2;rv()},mo(a){S.r.mo+=+a.dataset.v;rv()},dpick(a){const[y,m,d]=a.dataset.v.split('-').map(Number);S.r.d=new Date(y,m,d);S.r.t=null;S.r.s=3;rv()},tpick(a){S.r.t=+a.dataset.v;rv()},rgo(a){S.r.s=+a.dataset.v;rv()},rdv0(){rdv()},
 ics(){const v=ev(),x=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Studio Prism//RDV//FR','BEGIN:VEVENT','UID:'+S.r.ref+'@studioprism','DTSTAMP:'+v.z(Date.now()),'DTSTART:'+v.z(v.s),'DTEND:'+v.z(v.e),'SUMMARY:'+v.t,'DESCRIPTION:'+v.d,'BEGIN:VALARM','TRIGGER:-PT1H','ACTION:DISPLAY','DESCRIPTION:Rappel','END:VALARM','END:VEVENT','END:VCALENDAR'].join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([x],{type:'text/calendar'}));a.download='studio-prism-rdv.ics';a.click()},
 cat(a){const i=+a.dataset.v;a.classList.toggle('on');S.v3.meshes.forEach(m=>{if(m.userData.cat==i)m.visible=a.classList.contains('on')})},rst(){S.v3.reset()},
 shp(a){const m=S.v3.main;m.geometry.dispose();m.geometry=[new THREE.CylinderGeometry(1,1,1.5,6),new THREE.BoxGeometry(1.4,1.4,1.4),new THREE.TorusKnotGeometry(.8,.28,80,12)][a.dataset.v]},
 wire(){const m=S.v3.main.material;m.wireframe=!m.wireframe},auto(){S.v3.auto=!S.v3.auto},col(a){S.v3.main.material.color.set('#'+a.dataset.v)},ang(a){const v=S.v3,r=[[0,0],[1.5708,0],[0,1.5708],[.5,.6]][+a.dataset.v];v.auto=false;v.g.rotation.set(r[0],r[1],0)},zm(a){const g=S.v3.g;g.scale.setScalar(Math.min(2,Math.max(.5,g.scale.x*(a.dataset.v>0?1.2:.83))))}};
document.addEventListener('click',e=>{const a=e.target.closest('[data-a]');if(a)A[a.dataset.a]?.(a);else if(e.target.classList.contains('mod'))A.x();const r=e.target.closest('label.chip input[name=t]');if(r){S.dq=r.value;document.querySelectorAll('label.chip').forEach(l=>l.classList.toggle('on',l.contains(r)));ops()}});
document.addEventListener('change',e=>{if(e.target.closest('#ops,#dl'))est()});
document.addEventListener('pointermove',e=>{const c=e.target.closest?.('.card');if(!c)return;const b=c.getBoundingClientRect(),x=(e.clientX-b.left)/b.width,y=(e.clientY-b.top)/b.height;c.style.setProperty('--x',x*100+'%');c.style.setProperty('--y',y*100+'%')});
document.addEventListener('submit',e=>{e.preventDefault();const f=e.target.dataset.f,id=()=>Math.random().toString(36).slice(2,8).toUpperCase();
 if(f=='cmd'){if(S.step<3){S.step++;commande()}else{S.last='PRISM-'+id();cart=[];badge();S.step=1;go('#/confirmation-commande')}}
 if(f=='devis'){S.last='DEV-'+id();go('#/merci-devis')}
 if(f=='asu'||f=='asi')return authSubmit(e.target,f=='asu');if(f=='ct'){S.last='MSG-'+id();go('#/merci-contact')}
 if(f=='tck')$('#tk').innerHTML=`<div class="panel" style="margin-top:16px">Ticket créé : <b>TCK-${id()}</b>. Conservez cette référence pour le suivi.</div>`;
 if(f=='rdv'){const fd=new FormData(e.target);S.r.f={n:fd.get('n'),e:fd.get('e'),c:fd.get('c'),m:fd.get('m'),l:fd.get('l'),fl:(fd.get('fi')||{}).name||''};S.r.ref='RDV-'+id();S.r.s=5;rv();scrollTo(0,0)}});
const hh=()=>{const e=document.querySelector('header');e.classList.contains('sc')||document.documentElement.style.setProperty('--hh',e.offsetHeight+'px')};hh();addEventListener('resize',hh);try{new ResizeObserver(hh).observe(document.querySelector('header'))}catch(e){}

/* ---- V6 : thème, header, mini-panier, animation panier ---- */
const hs=()=>document.querySelector('header').classList.toggle('sc',scrollY>40);addEventListener('scroll',hs,{passive:true});hs();
const bump=()=>{const c=$('#cc');c.classList.remove('bump');void c.offsetWidth;c.classList.add('bump')};
const setInert=v=>['header','#v','footer'].forEach(q=>{const e=$(q);e&&(e.inert=v)});
function fly(src,done){const t=$('#cl'),r=src&&src.getBoundingClientRect();if(rmo()||!t||!r||!r.width||!n0(r)){done();return}
 const d=t.getBoundingClientRect(),n=document.createElement('div');n.className='fly';n.innerHTML=src.innerHTML;Object.assign(n.style,{left:r.left+'px',top:r.top+'px',width:r.width+'px',height:r.height+'px'});document.body.appendChild(n);
 const dx=d.left+d.width/2-(r.left+r.width/2),dy=d.top+d.height/2-(r.top+r.height/2);
 n.animate([{transform:'none',opacity:1},{transform:`translate(${dx*.5}px,${dy*.5-40}px) scale(.5)`,opacity:.95,offset:.55},{transform:`translate(${dx}px,${dy}px) scale(.08)`,opacity:.2}],{duration:650,easing:'cubic-bezier(.5,0,.7,.4)'}).finished.then(()=>{n.remove();done()},()=>{n.remove();done()})}
const n0=r=>r.bottom>0&&r.top<innerHeight;
function mcOpen(l,q){const m=$('#mc'),b=$('#mcb');$('#mcbody').innerHTML=`<p class="mok">✓ Produit ajouté</p><div class="ml"><div class="mth">${art(l.n)}</div><div><b>${l.n}</b><br><small class="mut">${l.mat} · ${l.col}</small><br>${q} × ${E(l.pr)}</div></div><p class="mut" style="font-size:14px">${cart.reduce((a,x)=>a+x.q,0)} article(s) dans le panier</p><div class="mf"><div class="mrow"><span>Sous-total</span><span>${E(sub())}</span></div><a class="btn b1" href="#/panier" data-a="mcx">Voir le panier</a><button class="btn b4" data-a="mcx">Continuer mes achats</button></div>`;
 m._f=document.activeElement;m.hidden=b.hidden=false;setInert(true);requestAnimationFrame(()=>requestAnimationFrame(()=>{m.classList.add('open');b.classList.add('open');m.querySelector('.mcc').focus()}))}
A.mcx=()=>{const m=$('#mc'),b=$('#mcb');if(m.hidden)return;m.classList.remove('open');b.classList.remove('open');setInert(false);setTimeout(()=>{m.hidden=b.hidden=true},rmo()?0:380);m._f&&m._f.focus&&m._f.focus()};
document.addEventListener('keydown',e=>{const m=$('#mc');if(m.hidden)return;if(e.key=='Escape')A.mcx();if(e.key=='Tab'){const f=[...m.querySelectorAll('a[href],button')],i=f.indexOf(document.activeElement);if(e.shiftKey&&i<1){f[f.length-1].focus();e.preventDefault()}else if(!e.shiftKey&&(i<0||i==f.length-1)){f[0].focus();e.preventDefault()}}});
const lgo=(k,alt,c='',a='')=>`<div class="logo-showcase ${c}" ${a}><img src="${IMG[k]}" alt="${alt}" loading="lazy" decoding="async"></div>`;

/* ===== V12 ===== */

const UX={app:['Prism App réunit les applications web et mobiles, les interfaces, les outils numériques et les prototypes de Studio Prism. Mieux vaut souvent un outil simple, pensé pour l’usage réel, qu’un logiciel générique : il se teste tôt, puis évolue avec les besoins. ArchiVision s’inscrit dans cette branche.',['Applications web et mobiles','Interfaces et parcours UX / UI','Applications métier et outils internes','Prototypes à valider avant le développement complet'],'Découvrir Prism App'],
p3d:['Prism 3D est l’univers de Studio Prism consacré au passage du numérique vers le réel : concevoir, visualiser, puis transformer un modèle numérique en objet concret. On y modélise en 3D et en CAO, on visualise le modèle avant fabrication, puis on prototype et on imprime, à l’unité ou en petites séries. Studio Prism l’a créé pour que ses modèles ne restent pas à l’écran : une pièce peut être tenue en main, testée et ajustée.',['Modélisation 3D et CAO','Visualisation avant fabrication','Prototypage et conception d’objets','Impression 3D (PLA, PETG) et petites séries'],'Découvrir Prism 3D'],
game:['Prism Game est l’univers créatif et expérimental de Studio Prism autour du jeu et des expériences interactives. Studio Prism n’y agit pas comme une agence de jeux vidéo : c’est un terrain d’exploration pour tester des mécaniques de gameplay, construire des environnements en 3D temps réel et monter des prototypes, notamment sur Roblox lorsque le projet s’y prête. Cette branche existe parce que le jeu est un excellent banc d’essai pour l’interaction, le rendu temps réel et de nouvelles façons de raconter en 3D.',['Mécaniques et gameplay','Environnements 3D temps réel','Prototypes jouables','Concepts d’univers (Roblox lorsque pertinent)'],'Découvrir Prism Game'],
av:['Le projet part du modèle BIM, avec l’IFC comme format principal, et en propose une lecture 3D : navigation, coupes, isolation par catégories, données des éléments et mesures. La réalité augmentée, puis virtuelle, doit ensuite permettre de la confronter au site, selon la feuille de route. ArchiVision s’adresse aux acteurs de la construction qui veulent comprendre un projet sans passer par un logiciel de conception.',['Explorer la maquette numérique','Isoler et analyser les éléments','Mesurer distances et dimensions','Consulter la maquette en réalité augmentée'],'Découvrir ArchiVision']};
const uxb=k=>`<div><p class="k">${UV[k][0]}</p><p class="lead2">${UV[k][1]}</p><p>${UX[k][0]}</p><p class="mt2" style="margin:16px 0 6px">Ce que Studio Prism y fait</p><ul class="uxl">${UX[k][1].map(t=>`<li>${t}</li>`).join('')}</ul></div>`;
const FG=['Shift Factory','Sky Islands','PRISM: The Shattered World'];
const prjSec=()=>`<section><div class="w"><div class="k">Projets</div><h2 class="rv">Projets</h2><p class="mut rv" style="max-width:620px;margin:-20px 0 32px">Un projet en conception et trois concepts Prism Game. Ce sont des projets du studio, pas des réalisations pour des clients.</p><div class="pf"><a class="pf0 rv" href="#/projets/archivision">${lgo('av','Logo ArchiVision — Architecture en réalité augmentée','ls-f')}<div class="t"><span class="tag">Projet principal</span><span class="tag">En conception</span><h3>ArchiVision</h3><p class="mt2">${UV.av[0]}</p><p>${UV.av[1]}</p><span class="btn bw ar">Découvrir ArchiVision</span></div></a>${FG.map((n,i)=>{const x=G.find(g=>g[0]==n);return `<a class="pf${i+1} rv" href="#/prism-game/${slug(n)}"><div class="im ig">${art(n)}</div><div class="t"><span class="tag">Concept Prism Game</span><h3>${n}</h3><p class="mt2">${x[1]}</p><p>${x[2]}</p></div></a>`}).join('')}</div></div></section>`;
/* Comptes (connexion, inscription, administration) : voir js/account.js, js/auth.js, js/admin.js. */
Object.assign(LG,{'conditions-utilisation':'Conditions d’utilisation'});
const LK={'mentions-legales':'ml',confidentialite:'pc','politique-confidentialite':'pc','conditions-utilisation':'cu',cgu:'cu','cgv-cgu':'cu',cgv:'cu',cookies:'ck'};
const LT={ml:[['Éditeur du site','Studio Prism, studio créatif et technologique fondé par Kéliann MAUGER et Paul COCAGNE. Forme juridique : [À COMPLÉTER]. SIRET : [À COMPLÉTER]. Adresse : [À COMPLÉTER].'],['Directeur de la publication','[À COMPLÉTER]'],['Contact','Via le <a class="more" href="#/contact">formulaire de contact</a>. Adresse e-mail : [À COMPLÉTER].'],['Hébergeur','Nom, adresse et contact de l’hébergeur : [À COMPLÉTER].'],['Propriété intellectuelle','Les textes, logos (Studio Prism, ArchiVision, Prism 3D, Prism App, Prism Game), visuels et contenus du site sont la propriété de Studio Prism, sauf mention contraire. Toute reproduction sans autorisation est interdite.'],['Statut des projets présentés','ArchiVision (en conception) et les concepts Prism Game et Prism 3D sont des projets de Studio Prism, et non des réalisations pour des clients.']],
pc:[['Responsable du traitement','Studio Prism — [À COMPLÉTER : identité et adresse].'],['Données concernées','Les informations saisies dans les formulaires du site (contact, devis, rendez-vous, support) : nom, adresse e-mail, message, pièce jointe éventuelle. Dans la version actuelle, ces formulaires ne sont pas encore reliés à un service d’envoi [À COMPLÉTER à la mise en ligne]. La création d’un compte Studio Prism enregistre : prénom, nom, adresse e-mail, type de compte (particulier ou entreprise) et, pour une entreprise, nom, e-mail, fonction, téléphone et site internet éventuels et nombre d’utilisateurs souhaité, ainsi que les dates de création et de dernière connexion.'],['Finalités','Répondre à vos demandes, établir une estimation, organiser un rendez-vous, gérer votre compte Studio Prism et vos accès aux services (dont ArchiVision).'],['Base légale et durée de conservation','[À COMPLÉTER]'],['Destinataires','Membres de Studio Prism. Prestataires techniques éventuels : [À COMPLÉTER].'],['Vos droits','Vous pouvez demander l’accès, la rectification, l’effacement, la limitation ou la portabilité de vos données, et vous opposer à leur traitement, en écrivant à : [À COMPLÉTER]. Vous pouvez aussi saisir la CNIL.']],
cu:[['Objet','Ces conditions encadrent l’utilisation du site de Studio Prism et de ses pages de présentation.'],['Accès au site','Le site est accessible librement. Studio Prism peut le modifier ou en suspendre l’accès, notamment pour maintenance.'],['Comptes Studio Prism','Un compte Studio Prism, particulier ou entreprise, donne accès aux services de Studio Prism, dont ArchiVision. La formule associée (Free, Pro ou Pro Entreprise) est attribuée par Studio Prism. Règles d’usage du compte : [À COMPLÉTER].'],['Contenus et projets','Les informations présentées sont indicatives. Les projets en conception ou en concept peuvent évoluer.'],['Devis et prestations','Toute prestation fait l’objet d’un devis personnalisé. Conditions : [À COMPLÉTER].'],['Responsabilité','[À COMPLÉTER]'],['Droit applicable','[À COMPLÉTER]']],
ck:[['Cookies et traceurs','Dans sa version actuelle, le site ne déclare aucun cookie publicitaire ni outil de mesure d’audience [À VÉRIFIER avant mise en ligne].'],['Ressources tierces','Le site charge la police Inter (Google Fonts) et, sur certaines pages, la bibliothèque 3D three.js (cdnjs) ; la gestion des comptes charge les bibliothèques Firebase (Google). Ces services reçoivent votre adresse IP lors du chargement.'],['Gérer vos choix','Vous pouvez paramétrer ou bloquer les cookies depuis votre navigateur. Si des traceurs soumis à consentement sont ajoutés, un module de choix sera mis en place : [À COMPLÉTER].'],['Contact','Une question ? Le <a class="more" href="#/contact">formulaire de contact</a> est à votre disposition.']]};

/* ===== Abonnements : la page publique et « Mon compte » sont dans js/platform.js ; les offres et leurs PRIX vivent dans Firestore ===== */
/* Tranches « nombre de comptes » de l'inscription Entreprise. Elles sont aussi validées par firebase/firestore.rules (tierOk) et par
   functions/handlers.js (TIERS) : à modifier aux trois endroits. */
const SUBSCRIPTION_CONFIG={plans:{PRO_ENTREPRISE:{tiers:[{id:'1',label:'1 utilisateur',short:'1',limit:1},{id:'2-10',label:'2 à 10 utilisateurs',short:'2–10',limit:10},{id:'11-25',label:'11 à 25 utilisateurs',short:'11–25',limit:25},{id:'26-50',label:'26 à 50 utilisateurs',short:'26–50',limit:50},{id:'51-100',label:'51 à 100 utilisateurs',short:'51–100',limit:100},{id:'100+',label:'Plus de 100 utilisateurs',short:'100+',limit:null}]}}};
const proCta=()=>`<div class="cz-pro"><p class="cz-q">Vous souhaitez aller plus loin ?</p><a class="btn cz-o ar" href="#/abonnements/archivision">Voir les abonnements</a></div>`;
/* ===== V13 : motifs (≥4 par page) et 6 blocs ===== */
const GL={plan:'M8 88V30l22-14 40 10 22-6v68zM30 16v72M70 26v62M8 58h84',cube:'M50 10l36 20v40L50 90 14 70V30zM50 10v40l36 20M50 50L14 30',wire:'M20 30l30-18 30 18v36L50 84 20 66zM20 30l30 18 30-18M50 48v36',axes:'M20 80V20M20 80h60M20 80l24-22M16 26l4-8 4 8M74 76l8 4-8 4',mesh:'M10 80L50 10l40 70zM30 45h40M20 62h60M50 10v70',ui:'M10 20h80v60H10zM10 34h80M20 27h4M30 27h4M22 46h30M22 58h46',code:'M32 30L12 50l20 20M68 30l20 20-20 20M56 24L44 76',cursor:'M30 12l8 66 14-16 18 22 8-6-18-22 20-4z',link:'M10 70a10 10 0 1 0 20 0a10 10 0 1 0-20 0M70 30a10 10 0 1 0 20 0a10 10 0 1 0-20 0M28 62l44-24',pad:'M10 40l8-12h64l8 12 6 34-12 10-14-16H30L16 84 4 74zM28 46h14M35 39v14',grid:'M10 25h80M10 50h80M10 75h80M25 10v80M50 10v80M75 10v80',frame:'M10 30V10h20M70 10h20v20M90 70v20H70M30 90H10V70M35 50h30M50 35v30',target:'M50 10a40 40 0 1 0 .1 0M50 30a20 20 0 1 0 .1 0M50 5v15M50 80v15M5 50h15M80 50h15',tool:'M20 80l36-36M52 28a16 16 0 0 1 22-8l-10 10 6 6 10-10a16 16 0 0 1-22 22',ruler:'M10 62L62 10l28 28L38 90zM26 50l10 10M38 38l10 10M50 26l10 10',ar:'M10 30V10h20M70 10h20v20M90 70v20H70M30 90H10V70M50 30l20 12v22L50 76 30 64V42zM50 52v24',pin:'M50 90S22 58 22 38a28 28 0 0 1 56 0c0 20-28 52-28 52zM50 28a10 10 0 1 0 .1 0',msg:'M10 20h80v46H44L24 84V66H10zM24 36h52M24 48h36',cal:'M12 22h76v66H12zM12 40h76M30 12v18M70 12v18M26 54h10M46 54h10M66 54h10M26 70h10M46 70h10',clock:'M50 10a40 40 0 1 0 .1 0M50 28v24l16 10',user:'M50 14a16 16 0 1 0 .1 0M18 88a32 28 0 0 1 64 0z',team:'M30 22a12 12 0 1 0 .1 0M70 22a12 12 0 1 0 .1 0M6 70a24 22 0 0 1 48 0zM46 70a24 22 0 0 1 48 0z',key:'M30 40a18 18 0 1 0 .1 0M46 52l40 30M72 70l-8 8M82 80l-8 8',lock:'M24 44h52v44H24zM34 44V30a16 16 0 0 1 32 0v14M50 62v10',plus:'M50 14v72M14 50h72',folder:'M10 25h30l8 10h42v52H10zM10 45h80',check:'M50 10a40 40 0 1 0 .1 0M30 52l14 14 28-30',card:'M8 24h84v52H8zM8 40h84M18 62h24',layers:'M50 12l40 20-40 20L10 32zM10 50l40 20 40-20M10 68l40 20 40-20',bars:'M14 86V50h16v36M42 86V24h16v62M70 86V38h16v48M8 88h84',eye:'M6 50C22 26 78 26 94 50 78 74 22 74 6 50zM50 38a12 12 0 1 0 .1 0',clip:'M24 16h52v72H24zM38 10h24v12H38zM36 44h28M36 58h28M36 72h16'};
const gl=(n,c='')=>`<svg class="${c}" viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"><path d="${GL[n]}"/></svg>`;
GL.doc='M24 8h38l18 18v66H24zM62 8v18h18M36 44h36M36 58h36M36 72h24';GL.sign='M12 70c10-30 18-30 22-10s10 10 20-8M12 86h76';GL.shield='M50 8l34 12v26c0 22-16 38-34 46C32 84 16 68 16 46V20z';GL.db='M20 24a30 12 0 1 0 60 0a30 12 0 1 0-60 0M20 24v52a30 12 0 0 0 60 0V24M20 50a30 12 0 0 0 60 0';GL.gear='M50 34a16 16 0 1 0 .1 0M50 6v14M50 80v14M6 50h14M80 50h14M20 20l10 10M70 70l10 10M80 20L70 30M30 70L20 80';GL.scale='M50 12v70M20 82h60M18 30h64M18 30l-10 26h20zM82 30l-10 26h20z';
const SETS={ml:['doc','folder','sign','check'],pc:['lock','shield','db','key'],cu:['doc','check','scale','sign'],ck:['db','gear','ui','lock'],hm:['plan','cube','ui','pad'],av:['plan','ar','ruler','grid'],p3:['wire','axes','mesh','cube'],ap:['ui','code','cursor','link'],pg:['pad','grid','cube','link'],sv:['tool','code','plan','cube'],pj:['frame','target','cube','plan'],eq:['team','link','frame','user'],ct:['pin','msg','link','grid'],rv:['cal','clock','plan','grid'],ab:['folder','check','card','user'],cn:['key','user','lock','link'],ins:['user','plus','check','frame'],df:['grid','link','frame','cube']};
const mkk=k=>k==''?'hm':/^mentions/.test(k)?'ml':/^(confidentialite|politique)/.test(k)?'pc':/^(conditions|cgu|cgv)/.test(k)?'cu':k=='cookies'?'ck':/^(archivision|compte)\/connexion$/.test(k)||k=='compte'||/^admin/.test(k)?'cn':/^(archivision|compte)\/inscription$/.test(k)?'ins':/^(abonnement|paiement|mon-abonnement)/.test(k)?'ab':/^(projets\/archivision|archivision)/.test(k)?'av':/^prism-3d/.test(k)?'p3':k=='prism-app'?'ap':/^prism-game/.test(k)?'pg':/^services/.test(k)?'sv':k=='projets'?'pj':/^a-propos/.test(k)?'eq':/^contact/.test(k)?'ct':/^rendez-vous/.test(k)?'rv':'df';
const mo=()=>{const k=CUR,h=[...k].reduce((a,c)=>a+c.charCodeAt(0),0),fl=h%2,T=k==''?[24,45,66,86]:[4+h%6,27+h%9,53+h%8,80+h%7];return `<div class="mo" aria-hidden="true">${SETS[mkk(k)].map((n,i)=>`<i style="top:${T[i]}%;${(i+fl)%2?'left:'+(-2+h%4)+'%':'right:'+(-1+h%4)+'%'};width:${110+((h+i*37)%50)}px">${gl(n).replace('<svg ','<svg style="transform:rotate('+(((h+i*3)%5-2)*7)+'deg)" ')}</i>`).join('')}</div>`};
const fx=()=>`<div class="fx">${[['Explorer','Naviguer dans la maquette.','cube'],['Isoler','Masquer certaines catégories.','layers'],['Analyser','Sélectionner un élément et consulter ses informations.','bars'],['Mesurer','Mesurer des distances et des dimensions.','ruler'],['Comprendre','Visualiser le bâtiment sous différentes vues.','eye'],['Préparer','Utiliser la maquette comme support de compréhension du projet.','clip']].map(([t,d,i],n)=>`<div class="fb" tabindex="0"><div class="ft"><span class="no">0${n+1}</span><h3>${t}</h3><p>${d}</p></div>${gl(i,'fi')}</div>`).join('')}</div>`;
/* ===== V13 : textes légaux complétés ===== */
LG.cookies='Cookies & données';
LT.ml.push(['Responsabilité','Studio Prism s’efforce de fournir des informations exactes mais ne garantit pas l’absence d’erreurs. Les projets présentés sont indicatifs et peuvent évoluer.']);
LT.pc.push(['Compte utilisateur','Compte Studio Prism : prénom, nom, adresse e-mail et mot de passe. Le mot de passe est géré par Firebase Authentication (Google) ; Studio Prism ne le lit ni ne le stocke. Le profil du compte est conservé dans Cloud Firestore. Durée de conservation : [À COMPLÉTER].'],['Sécurité','Studio Prism met en œuvre des mesures raisonnables pour protéger les données. Détail : [À COMPLÉTER].'],['Services tiers','Police Google Fonts, bibliothèque three.js (cdnjs) et Firebase (Google : authentification et base de données des comptes ; localisation des données et transferts : [À COMPLÉTER]). Aucun paiement en ligne n’est proposé actuellement : les licences sont activées par Studio Prism.']);
LT.cu.splice(2,0,['Utilisation d’ArchiVision','ArchiVision est un outil d’exploration et de visualisation de maquettes numériques destiné aux professionnels ; il ne remplace ni les outils de conception ni les contrôles réglementaires.'],['Propriété intellectuelle','Les logos, textes et visuels de Studio Prism sont protégés. Droits sur les fichiers déposés par les utilisateurs : [À COMPLÉTER].']);
LT.cu.push(['Disponibilité','Le service est fourni sans garantie de disponibilité continue : [À COMPLÉTER].'],['Abonnement et résiliation','Les formules proposées, leurs fonctionnalités, leurs prix et leur périodicité sont indiqués sur la page Abonnements. Aucun paiement en ligne n’est ouvert : l’activation d’une formule se fait avec Studio Prism. Conditions de facturation et de résiliation : [À COMPLÉTER].'],['Modification des conditions','Studio Prism peut modifier ces conditions ; la date de mise à jour figure en haut de la page.']);
LT.ck.push(['Cookies techniques','Le site ne dépose pas de cookie. Lorsque vous êtes connecté, Firebase Authentication conserve votre session dans le stockage du navigateur (IndexedDB), strictement nécessaire au service de connexion [À VÉRIFIER].'],['Cookies analytiques','Aucun outil d’analyse n’est utilisé actuellement. En cas d’ajout, votre consentement sera demandé.']);
